# Leo colorizer control file for apacheconf mode.

# Properties for apacheconf mode.
properties = {
	"lineComment": "#",
}

# Keywords dict for apacheconf_main ruleset.
apacheconf_main_keywords_dict = {
	"AcceptMutex": "keyword1",
	"AcceptPathInfo": "keyword1",
	"AccessFileName": "keyword1",
	"Action": "keyword1",
	"AddAlt": "keyword1",
	"AddAltByEncoding": "keyword1",
	"AddAltByType": "keyword1",
	"AddCharset": "keyword1",
	"AddDefaultCharset": "keyword1",
	"AddDescription": "keyword1",
	"AddEncoding": "keyword1",
	"AddHandler": "keyword1",
	"AddIcon": "keyword1",
	"AddIconByEncoding": "keyword1",
	"AddIconByType": "keyword1",
	"AddInputFilter": "keyword1",
	"AddLanguage": "keyword1",
	"AddModule": "keyword4",
	"AddModuleInfo": "keyword1",
	"AddOutputFilter": "keyword1",
	"AddOutputFilterByType": "keyword1",
	"AddType": "keyword1",
	"Alias": "keyword1",
	"AliasMatch": "keyword1",
	"AllowCONNECT": "keyword1",
	"AllowEncodedSlashes": "keyword1",
	"AuthDigestNcCheck": "keyword1",
	"AuthDigestShmemSize": "keyword1",
	"AuthLDAPCharsetConfig": "keyword1",
	"BS2000Account": "keyword1",
	"BrowserMatch": "keyword1",
	"BrowserMatchNoCase": "keyword1",
	"CacheDefaultExpire": "keyword1",
	"CacheDirLength": "keyword1",
	"CacheDirLevels": "keyword1",
	"CacheDisable": "keyword1",
	"CacheEnable": "keyword1",
	"CacheExpiryCheck": "keyword1",
	"CacheFile": "keyword1",
	"CacheForceCompletion": "keyword1",
	"CacheGcClean": "keyword1",
	"CacheGcDaily": "keyword1",
	"CacheGcInterval": "keyword1",
	"CacheGcMemUsage": "keyword1",
	"CacheGcUnused": "keyword1",
	"CacheIgnoreCacheControl": "keyword1",
	"CacheIgnoreNoLastMod": "keyword1",
	"CacheLastModifiedFactor": "keyword1",
	"CacheMaxExpire": "keyword1",
	"CacheMaxFileSize": "keyword1",
	"CacheMinFileSize": "keyword1",
	"CacheNegotiatedDocs": "keyword1",
	"CacheRoot": "keyword1",
	"CacheSize": "keyword1",
	"CacheTimeMargin": "keyword1",
	"CharsetDefault": "keyword1",
	"CharsetOptions": "keyword1",
	"CharsetSourceEnc": "keyword1",
	"CheckSpelling": "keyword1",
	"ChildPerUserID": "keyword1",
	"ClearModuleList": "keyword4",
	"ContentDigest": "keyword1",
	"CookieDomain": "keyword1",
	"CookieExpires": "keyword1",
	"CookieLog": "keyword1",
	"CookieName": "keyword1",
	"CookieStyle": "keyword1",
	"CookieTracking": "keyword1",
	"CoreDumpDirectory": "keyword1",
	"CustomLog": "keyword1",
	"DavDepthInfinity": "keyword1",
	"DavLockDB": "keyword1",
	"DavMinTimeout": "keyword1",
	"DefaultIcon": "keyword1",
	"DefaultLanguage": "keyword1",
	"DefaultType": "keyword1",
	"DeflateBufferSize": "keyword1",
	"DeflateCompressionLevel": "keyword1",
	"DeflateFilterNote": "keyword1",
	"DeflateMemLevel": "keyword1",
	"DeflateWindowSize": "keyword1",
	"DirectoryIndex": "keyword1",
	"DocumentRoot": "keyword1",
	"EnableMMAP": "keyword1",
	"EnableSendfile": "keyword1",
	"ErrorDocument": "keyword1",
	"ErrorLog": "keyword1",
	"Example": "keyword1",
	"ExpiresActive": "keyword1",
	"ExpiresByType": "keyword1",
	"ExpiresDefault": "keyword1",
	"ExtFilterDefine": "keyword1",
	"ExtendedStatus": "keyword1",
	"FileETag": "keyword1",
	"ForceLanguagePriority": "keyword1",
	"Group": "keyword1",
	"Header": "keyword1",
	"HeaderName": "keyword1",
	"HostnameLookups": "keyword1",
	"ISAPIAppendLogToErrors": "keyword1",
	"ISAPIAppendLogToQuery": "keyword1",
	"ISAPICacheFile": "keyword1",
	"ISAPIFakeAsync": "keyword1",
	"ISAPILogNotSupported": "keyword1",
	"ISAPIReadAheadBuffer": "keyword1",
	"IdentityCheck": "keyword1",
	"ImapBase": "keyword1",
	"ImapDefault": "keyword1",
	"ImapMenu": "keyword1",
	"Include": "keyword1",
	"IndexIgnore": "keyword1",
	"IndexOptions": "keyword1",
	"IndexOrderDefault": "keyword1",
	"KeepAlive": "keyword1",
	"KeepAliveTimeout": "keyword1",
	"LDAPCacheEntries": "keyword1",
	"LDAPCacheTTL": "keyword1",
	"LDAPOpCacheEntries": "keyword1",
	"LDAPOpCacheTTL": "keyword1",
	"LDAPSharedCacheSize": "keyword1",
	"LDAPTrustedCA": "keyword1",
	"LDAPTrustedCAType": "keyword1",
	"LanguagePriority": "keyword1",
	"LimitInternalRecursion": "keyword1",
	"LimitRequestBody": "keyword1",
	"LimitRequestFields": "keyword1",
	"LimitRequestFieldsize": "keyword1",
	"LimitRequestLine": "keyword1",
	"LimitXMLRequestBody": "keyword1",
	"Listen": "keyword1",
	"ListenBacklog": "keyword1",
	"LoadFile": "keyword1",
	"LoadModule": "keyword1",
	"LockFile": "keyword1",
	"LogFormat": "keyword1",
	"LogLevel": "keyword1",
	"MCacheMaxObjectCount": "keyword1",
	"MCacheMaxObjectSize": "keyword1",
	"MCacheMaxStreamingBuffer": "keyword1",
	"MCacheMinObjectSize": "keyword1",
	"MCacheRemovalAlgorithm": "keyword1",
	"MCacheSize": "keyword1",
	"MMapFile": "keyword1",
	"MaxClients": "keyword1",
	"MaxKeepAliveRequests": "keyword1",
	"MaxMemFree": "keyword1",
	"MaxRequestsPerChild": "keyword1",
	"MaxRequestsPerThread": "keyword1",
	"MaxSpareServers": "keyword1",
	"MaxSpareThreads": "keyword1",
	"MaxThreads": "keyword1",
	"MaxThreadsPerChild": "keyword1",
	"MetaDir": "keyword1",
	"MetaFiles": "keyword1",
	"MetaSuffix": "keyword1",
	"MimeMagicFile": "keyword1",
	"MinSpareServers": "keyword1",
	"MinSpareThreads": "keyword1",
	"MultiviewsMatch": "keyword1",
	"NWSSLTrustedCerts": "keyword1",
	"NameVirtualHost": "keyword1",
	"NoProxy": "keyword1",
	"NumServers": "keyword1",
	"Options": "keyword1",
	"PassEnv": "keyword1",
	"PidFile": "keyword1",
	"Port": "keyword4",
	"ProtocolEcho": "keyword1",
	"ProxyBadHeader": "keyword1",
	"ProxyBlock": "keyword1",
	"ProxyDomain": "keyword1",
	"ProxyErrorOverride": "keyword1",
	"ProxyIOBufferSize": "keyword1",
	"ProxyMaxForwards": "keyword1",
	"ProxyPass": "keyword1",
	"ProxyPassReverse": "keyword1",
	"ProxyPreserveHost": "keyword1",
	"ProxyReceiveBufferSize": "keyword1",
	"ProxyRemote": "keyword1",
	"ProxyRemoteMatch": "keyword1",
	"ProxyRequests": "keyword1",
	"ProxyTimeout": "keyword1",
	"ProxyVia": "keyword1",
	"RLimitCPU": "keyword1",
	"RLimitMEM": "keyword1",
	"RLimitNPROC": "keyword1",
	"ReadmeName": "keyword1",
	"Redirect": "keyword1",
	"RedirectMatch": "keyword1",
	"RedirectPermanent": "keyword1",
	"RedirectTemp": "keyword1",
	"RequestHeader": "keyword1",
	"RewriteCond": "keyword1",
	"RewriteEngine": "keyword1",
	"RewriteLock": "keyword1",
	"RewriteLog": "keyword1",
	"RewriteLogLevel": "keyword1",
	"RewriteMap": "keyword1",
	"RewriteOptions": "keyword1",
	"RewriteRule": "keyword1",
	"SSIEndTag": "keyword1",
	"SSIErrorMsg": "keyword1",
	"SSIStartTag": "keyword1",
	"SSITimeFormat": "keyword1",
	"SSIUndefinedEcho": "keyword1",
	"SSLCACertificateFile": "keyword1",
	"SSLCACertificatePath": "keyword1",
	"SSLCARevocationFile": "keyword1",
	"SSLCARevocationPath": "keyword1",
	"SSLCertificateChainFile": "keyword1",
	"SSLCertificateFile": "keyword1",
	"SSLCertificateKeyFile": "keyword1",
	"SSLCipherSuite": "keyword1",
	"SSLEngine": "keyword1",
	"SSLMutex": "keyword1",
	"SSLOptions": "keyword1",
	"SSLPassPhraseDialog": "keyword1",
	"SSLProtocol": "keyword1",
	"SSLProxyCACertificateFile": "keyword1",
	"SSLProxyCACertificatePath": "keyword1",
	"SSLProxyCARevocationFile": "keyword1",
	"SSLProxyCARevocationPath": "keyword1",
	"SSLProxyCipherSuite": "keyword1",
	"SSLProxyEngine": "keyword1",
	"SSLProxyMachineCertificateFile": "keyword1",
	"SSLProxyMachineCertificatePath": "keyword1",
	"SSLProxyProtocol": "keyword1",
	"SSLProxyVerify": "keyword1",
	"SSLProxyVerifyDepth": "keyword1",
	"SSLRandomSeed": "keyword1",
	"SSLSessionCache": "keyword1",
	"SSLSessionCacheTimeout": "keyword1",
	"SSLVerifyClient": "keyword1",
	"SSLVerifyDepth": "keyword1",
	"ScoreBoardFile": "keyword1",
	"Script": "keyword1",
	"ScriptAlias": "keyword1",
	"ScriptAliasMatch": "keyword1",
	"ScriptInterpreterSource": "keyword1",
	"ScriptLog": "keyword1",
	"ScriptLogBuffer": "keyword1",
	"ScriptLogLength": "keyword1",
	"ScriptSock": "keyword1",
	"SecureListen": "keyword1",
	"SendBufferSize": "keyword1",
	"ServerAdmin": "keyword1",
	"ServerLimit": "keyword1",
	"ServerName": "keyword1",
	"ServerRoot": "keyword1",
	"ServerSignature": "keyword1",
	"ServerTokens": "keyword1",
	"ServerType": "keyword4",
	"SetEnv": "keyword1",
	"SetEnvIf": "keyword1",
	"SetEnvIfNoCase": "keyword1",
	"SetHandler": "keyword1",
	"SetInputFilter": "keyword1",
	"SetOutputFilter": "keyword1",
	"StartServers": "keyword1",
	"StartThreads": "keyword1",
	"SuexecUserGroup": "keyword1",
	"ThreadLimit": "keyword1",
	"ThreadStackSize": "keyword1",
	"ThreadsPerChild": "keyword1",
	"TimeOut": "keyword1",
	"TransferLog": "keyword1",
	"TypesConfig": "keyword1",
	"UnsetEnv": "keyword1",
	"UseCanonicalName": "keyword1",
	"User": "keyword1",
	"UserDir": "keyword1",
	"VirtualDocumentRoot": "keyword1",
	"VirtualDocumentRootIP": "keyword1",
	"VirtualScriptAlias": "keyword1",
	"VirtualScriptAliasIP": "keyword1",
	"XBitHack": "keyword1",
}

# Keywords dict for apacheconf_directive ruleset.
apacheconf_directive_keywords_dict = {
	"AcceptMutex": "keyword2",
	"AcceptPathInfo": "keyword2",
	"AccessFileName": "keyword2",
	"Action": "keyword2",
	"AddAlt": "keyword2",
	"AddAltByEncoding": "keyword2",
	"AddAltByType": "keyword2",
	"AddCharset": "keyword2",
	"AddDefaultCharset": "keyword2",
	"AddDescription": "keyword2",
	"AddEncoding": "keyword2",
	"AddHandler": "keyword2",
	"AddIcon": "keyword2",
	"AddIconByEncoding": "keyword2",
	"AddIconByType": "keyword2",
	"AddInputFilter": "keyword2",
	"AddLanguage": "keyword2",
	"AddModule": "keyword4",
	"AddModuleInfo": "keyword2",
	"AddOutputFilter": "keyword2",
	"AddOutputFilterByType": "keyword2",
	"AddType": "keyword2",
	"Alias": "keyword2",
	"AliasMatch": "keyword2",
	"Allow": "keyword2",
	"AllowCONNECT": "keyword2",
	"AllowEncodedSlashes": "keyword2",
	"AllowOverride": "keyword2",
	"Anonymous": "keyword2",
	"Anonymous_Authoritative": "keyword2",
	"Anonymous_LogEmail": "keyword2",
	"Anonymous_MustGiveEmail": "keyword2",
	"Anonymous_NoUserID": "keyword2",
	"Anonymous_VerifyEmail": "keyword2",
	"AuthAuthoritative": "keyword2",
	"AuthDBMAuthoritative": "keyword2",
	"AuthDBMGroupFile": "keyword2",
	"AuthDBMType": "keyword2",
	"AuthDBMUserFile": "keyword2",
	"AuthDigestAlgorithm": "keyword2",
	"AuthDigestDomain": "keyword2",
	"AuthDigestFile": "keyword2",
	"AuthDigestGroupFile": "keyword2",
	"AuthDigestNcCheck": "keyword2",
	"AuthDigestNonceFormat": "keyword2",
	"AuthDigestNonceLifetime": "keyword2",
	"AuthDigestQop": "keyword2",
	"AuthDigestShmemSize": "keyword2",
	"AuthGroupFile": "keyword2",
	"AuthLDAPAuthoritative": "keyword2",
	"AuthLDAPBindDN": "keyword2",
	"AuthLDAPBindPassword": "keyword2",
	"AuthLDAPCharsetConfig": "keyword2",
	"AuthLDAPCompareDNOnServer": "keyword2",
	"AuthLDAPDereferenceAliases": "keyword2",
	"AuthLDAPEnabled": "keyword2",
	"AuthLDAPFrontPageHack": "keyword2",
	"AuthLDAPGroupAttribute": "keyword2",
	"AuthLDAPGroupAttributeIsDN": "keyword2",
	"AuthLDAPRemoteUserIsDN": "keyword2",
	"AuthLDAPUrl": "keyword2",
	"AuthName": "keyword2",
	"AuthType": "keyword2",
	"AuthUserFile": "keyword2",
	"BS2000Account": "keyword2",
	"BrowserMatch": "keyword2",
	"BrowserMatchNoCase": "keyword2",
	"CGIMapExtension": "keyword2",
	"CacheDefaultExpire": "keyword2",
	"CacheDirLength": "keyword2",
	"CacheDirLevels": "keyword2",
	"CacheDisable": "keyword2",
	"CacheEnable": "keyword2",
	"CacheExpiryCheck": "keyword2",
	"CacheFile": "keyword2",
	"CacheForceCompletion": "keyword2",
	"CacheGcClean": "keyword2",
	"CacheGcDaily": "keyword2",
	"CacheGcInterval": "keyword2",
	"CacheGcMemUsage": "keyword2",
	"CacheGcUnused": "keyword2",
	"CacheIgnoreCacheControl": "keyword2",
	"CacheIgnoreNoLastMod": "keyword2",
	"CacheLastModifiedFactor": "keyword2",
	"CacheMaxExpire": "keyword2",
	"CacheMaxFileSize": "keyword2",
	"CacheMinFileSize": "keyword2",
	"CacheNegotiatedDocs": "keyword2",
	"CacheRoot": "keyword2",
	"CacheSize": "keyword2",
	"CacheTimeMargin": "keyword2",
	"CharsetDefault": "keyword2",
	"CharsetOptions": "keyword2",
	"CharsetSourceEnc": "keyword2",
	"CheckSpelling": "keyword2",
	"ChildPerUserID": "keyword2",
	"ClearModuleList": "keyword4",
	"ContentDigest": "keyword2",
	"CookieDomain": "keyword2",
	"CookieExpires": "keyword2",
	"CookieLog": "keyword2",
	"CookieName": "keyword2",
	"CookieStyle": "keyword2",
	"CookieTracking": "keyword2",
	"CoreDumpDirectory": "keyword2",
	"CustomLog": "keyword2",
	"Dav": "keyword2",
	"DavDepthInfinity": "keyword2",
	"DavLockDB": "keyword2",
	"DavMinTimeout": "keyword2",
	"DefaultIcon": "keyword2",
	"DefaultLanguage": "keyword2",
	"DefaultType": "keyword2",
	"DeflateBufferSize": "keyword2",
	"DeflateCompressionLevel": "keyword2",
	"DeflateFilterNote": "keyword2",
	"DeflateMemLevel": "keyword2",
	"DeflateWindowSize": "keyword2",
	"Deny": "keyword2",
	"DirectoryIndex": "keyword2",
	"DocumentRoot": "keyword2",
	"EnableMMAP": "keyword2",
	"EnableSendfile": "keyword2",
	"ErrorDocument": "keyword2",
	"ErrorLog": "keyword2",
	"Example": "keyword2",
	"ExpiresActive": "keyword2",
	"ExpiresByType": "keyword2",
	"ExpiresDefault": "keyword2",
	"ExtFilterDefine": "keyword2",
	"ExtFilterOptions": "keyword2",
	"ExtendedStatus": "keyword2",
	"FileETag": "keyword2",
	"ForceLanguagePriority": "keyword2",
	"ForceType": "keyword2",
	"Group": "keyword2",
	"Header": "keyword2",
	"HeaderName": "keyword2",
	"HostnameLookups": "keyword2",
	"ISAPIAppendLogToErrors": "keyword2",
	"ISAPIAppendLogToQuery": "keyword2",
	"ISAPICacheFile": "keyword2",
	"ISAPIFakeAsync": "keyword2",
	"ISAPILogNotSupported": "keyword2",
	"ISAPIReadAheadBuffer": "keyword2",
	"IdentityCheck": "keyword2",
	"ImapBase": "keyword2",
	"ImapDefault": "keyword2",
	"ImapMenu": "keyword2",
	"Include": "keyword2",
	"IndexIgnore": "keyword2",
	"IndexOptions": "keyword2",
	"IndexOrderDefault": "keyword2",
	"KeepAlive": "keyword2",
	"KeepAliveTimeout": "keyword2",
	"LDAPCacheEntries": "keyword2",
	"LDAPCacheTTL": "keyword2",
	"LDAPOpCacheEntries": "keyword2",
	"LDAPOpCacheTTL": "keyword2",
	"LDAPSharedCacheSize": "keyword2",
	"LDAPTrustedCA": "keyword2",
	"LDAPTrustedCAType": "keyword2",
	"LanguagePriority": "keyword2",
	"LimitInternalRecursion": "keyword2",
	"LimitRequestBody": "keyword2",
	"LimitRequestFields": "keyword2",
	"LimitRequestFieldsize": "keyword2",
	"LimitRequestLine": "keyword2",
	"LimitXMLRequestBody": "keyword2",
	"Listen": "keyword2",
	"ListenBacklog": "keyword2",
	"LoadFile": "keyword2",
	"LoadModule": "keyword2",
	"LockFile": "keyword2",
	"LogFormat": "keyword2",
	"LogLevel": "keyword2",
	"MCacheMaxObjectCount": "keyword2",
	"MCacheMaxObjectSize": "keyword2",
	"MCacheMaxStreamingBuffer": "keyword2",
	"MCacheMinObjectSize": "keyword2",
	"MCacheRemovalAlgorithm": "keyword2",
	"MCacheSize": "keyword2",
	"MMapFile": "keyword2",
	"MaxClients": "keyword2",
	"MaxKeepAliveRequests": "keyword2",
	"MaxMemFree": "keyword2",
	"MaxRequestsPerChild": "keyword2",
	"MaxRequestsPerThread": "keyword2",
	"MaxSpareServers": "keyword2",
	"MaxSpareThreads": "keyword2",
	"MaxThreads": "keyword2",
	"MaxThreadsPerChild": "keyword2",
	"MetaDir": "keyword2",
	"MetaFiles": "keyword2",
	"MetaSuffix": "keyword2",
	"MimeMagicFile": "keyword2",
	"MinSpareServers": "keyword2",
	"MinSpareThreads": "keyword2",
	"ModMimeUsePathInfo": "keyword2",
	"MultiviewsMatch": "keyword2",
	"NWSSLTrustedCerts": "keyword2",
	"NameVirtualHost": "keyword2",
	"NoProxy": "keyword2",
	"NumServers": "keyword2",
	"Options": "keyword2",
	"Order": "keyword2",
	"PassEnv": "keyword2",
	"PidFile": "keyword2",
	"ProtocolEcho": "keyword2",
	"ProxyBadHeader": "keyword2",
	"ProxyBlock": "keyword2",
	"ProxyDomain": "keyword2",
	"ProxyErrorOverride": "keyword2",
	"ProxyIOBufferSize": "keyword2",
	"ProxyMaxForwards": "keyword2",
	"ProxyPass": "keyword2",
	"ProxyPassReverse": "keyword2",
	"ProxyPreserveHost": "keyword2",
	"ProxyReceiveBufferSize": "keyword2",
	"ProxyRemote": "keyword2",
	"ProxyRemoteMatch": "keyword2",
	"ProxyRequests": "keyword2",
	"ProxyTimeout": "keyword2",
	"ProxyVia": "keyword2",
	"PythonDebug": "keyword3",
	"PythonHandler": "keyword3",
	"RLimitCPU": "keyword2",
	"RLimitMEM": "keyword2",
	"RLimitNPROC": "keyword2",
	"ReadmeName": "keyword2",
	"Redirect": "keyword2",
	"RedirectMatch": "keyword2",
	"RedirectPermanent": "keyword2",
	"RedirectTemp": "keyword2",
	"RemoveCharset": "keyword2",
	"RemoveEncoding": "keyword2",
	"RemoveHandler": "keyword2",
	"RemoveInputFilter": "keyword2",
	"RemoveLanguage": "keyword2",
	"RemoveOutputFilter": "keyword2",
	"RemoveType": "keyword2",
	"RequestHeader": "keyword2",
	"Require": "keyword2",
	"RewriteBase": "keyword2",
	"RewriteCond": "keyword2",
	"RewriteEngine": "keyword2",
	"RewriteLock": "keyword2",
	"RewriteLog": "keyword2",
	"RewriteLogLevel": "keyword2",
	"RewriteMap": "keyword2",
	"RewriteOptions": "keyword2",
	"RewriteRule": "keyword2",
	"SSIEndTag": "keyword2",
	"SSIErrorMsg": "keyword2",
	"SSIStartTag": "keyword2",
	"SSITimeFormat": "keyword2",
	"SSIUndefinedEcho": "keyword2",
	"SSLCACertificateFile": "keyword2",
	"SSLCACertificatePath": "keyword2",
	"SSLCARevocationFile": "keyword2",
	"SSLCARevocationPath": "keyword2",
	"SSLCertificateChainFile": "keyword2",
	"SSLCertificateFile": "keyword2",
	"SSLCertificateKeyFile": "keyword2",
	"SSLCipherSuite": "keyword2",
	"SSLEngine": "keyword2",
	"SSLMutex": "keyword2",
	"SSLOptions": "keyword2",
	"SSLPassPhraseDialog": "keyword2",
	"SSLProtocol": "keyword2",
	"SSLProxyCACertificateFile": "keyword2",
	"SSLProxyCACertificatePath": "keyword2",
	"SSLProxyCARevocationFile": "keyword2",
	"SSLProxyCARevocationPath": "keyword2",
	"SSLProxyCipherSuite": "keyword2",
	"SSLProxyEngine": "keyword2",
	"SSLProxyMachineCertificateFile": "keyword2",
	"SSLProxyMachineCertificatePath": "keyword2",
	"SSLProxyProtocol": "keyword2",
	"SSLProxyVerify": "keyword2",
	"SSLProxyVerifyDepth": "keyword2",
	"SSLRandomSeed": "keyword2",
	"SSLRequire": "keyword2",
	"SSLRequireSSL": "keyword2",
	"SSLSessionCache": "keyword2",
	"SSLSessionCacheTimeout": "keyword2",
	"SSLVerifyClient": "keyword2",
	"SSLVerifyDepth": "keyword2",
	"SVNIndexXSLT": "keyword3",
	"SVNParentPath": "keyword3",
	"SVNPath": "keyword3",
	"Satisfy": "keyword2",
	"ScoreBoardFile": "keyword2",
	"Script": "keyword2",
	"ScriptAlias": "keyword2",
	"ScriptAliasMatch": "keyword2",
	"ScriptInterpreterSource": "keyword2",
	"ScriptLog": "keyword2",
	"ScriptLogBuffer": "keyword2",
	"ScriptLogLength": "keyword2",
	"ScriptSock": "keyword2",
	"SecureListen": "keyword2",
	"SendBufferSize": "keyword2",
	"ServerAdmin": "keyword2",
	"ServerLimit": "keyword2",
	"ServerName": "keyword2",
	"ServerRoot": "keyword2",
	"ServerSignature": "keyword2",
	"ServerTokens": "keyword2",
	"SetEnv": "keyword2",
	"SetEnvIf": "keyword2",
	"SetEnvIfNoCase": "keyword2",
	"SetHandler": "keyword2",
	"SetInputFilter": "keyword2",
	"SetOutputFilter": "keyword2",
	"StartServers": "keyword2",
	"StartThreads": "keyword2",
	"SuexecUserGroup": "keyword2",
	"ThreadLimit": "keyword2",
	"ThreadStackSize": "keyword2",
	"ThreadsPerChild": "keyword2",
	"TimeOut": "keyword2",
	"TransferLog": "keyword2",
	"TypesConfig": "keyword2",
	"UnsetEnv": "keyword2",
	"UseCanonicalName": "keyword2",
	"User": "keyword2",
	"UserDir": "keyword2",
	"VirtualDocumentRoot": "keyword2",
	"VirtualDocumentRootIP": "keyword2",
	"VirtualScriptAlias": "keyword2",
	"VirtualScriptAliasIP": "keyword2",
	"XBitHack": "keyword2",
}

# Keywords dict for apacheconf_vhost ruleset.
apacheconf_vhost_keywords_dict = {
	"AcceptMutex": "keyword2",
	"AcceptPathInfo": "keyword2",
	"AccessFileName": "keyword2",
	"Action": "keyword2",
	"AddAlt": "keyword2",
	"AddAltByEncoding": "keyword2",
	"AddAltByType": "keyword2",
	"AddCharset": "keyword2",
	"AddDefaultCharset": "keyword2",
	"AddDescription": "keyword2",
	"AddEncoding": "keyword2",
	"AddHandler": "keyword2",
	"AddIcon": "keyword2",
	"AddIconByEncoding": "keyword2",
	"AddIconByType": "keyword2",
	"AddInputFilter": "keyword2",
	"AddLanguage": "keyword2",
	"AddModuleInfo": "keyword2",
	"AddOutputFilter": "keyword2",
	"AddOutputFilterByType": "keyword2",
	"AddType": "keyword2",
	"Alias": "keyword2",
	"AliasMatch": "keyword2",
	"AllowCONNECT": "keyword2",
	"AllowEncodedSlashes": "keyword2",
	"AssignUserID": "keyword2",
	"AuthDigestNcCheck": "keyword2",
	"AuthDigestShmemSize": "keyword2",
	"AuthLDAPCharsetConfig": "keyword2",
	"BS2000Account": "keyword2",
	"BrowserMatch": "keyword2",
	"BrowserMatchNoCase": "keyword2",
	"CacheDefaultExpire": "keyword2",
	"CacheDirLength": "keyword2",
	"CacheDirLevels": "keyword2",
	"CacheDisable": "keyword2",
	"CacheEnable": "keyword2",
	"CacheExpiryCheck": "keyword2",
	"CacheFile": "keyword2",
	"CacheForceCompletion": "keyword2",
	"CacheGcClean": "keyword2",
	"CacheGcDaily": "keyword2",
	"CacheGcInterval": "keyword2",
	"CacheGcMemUsage": "keyword2",
	"CacheGcUnused": "keyword2",
	"CacheIgnoreCacheControl": "keyword2",
	"CacheIgnoreNoLastMod": "keyword2",
	"CacheLastModifiedFactor": "keyword2",
	"CacheMaxExpire": "keyword2",
	"CacheMaxFileSize": "keyword2",
	"CacheMinFileSize": "keyword2",
	"CacheNegotiatedDocs": "keyword2",
	"CacheRoot": "keyword2",
	"CacheSize": "keyword2",
	"CacheTimeMargin": "keyword2",
	"CharsetDefault": "keyword2",
	"CharsetOptions": "keyword2",
	"CharsetSourceEnc": "keyword2",
	"CheckSpelling": "keyword2",
	"ChildPerUserID": "keyword2",
	"ContentDigest": "keyword2",
	"CookieDomain": "keyword2",
	"CookieExpires": "keyword2",
	"CookieLog": "keyword2",
	"CookieName": "keyword2",
	"CookieStyle": "keyword2",
	"CookieTracking": "keyword2",
	"CoreDumpDirectory": "keyword2",
	"CustomLog": "keyword2",
	"DavDepthInfinity": "keyword2",
	"DavLockDB": "keyword2",
	"DavMinTimeout": "keyword2",
	"DefaultIcon": "keyword2",
	"DefaultLanguage": "keyword2",
	"DefaultType": "keyword2",
	"DeflateBufferSize": "keyword2",
	"DeflateCompressionLevel": "keyword2",
	"DeflateFilterNote": "keyword2",
	"DeflateMemLevel": "keyword2",
	"DeflateWindowSize": "keyword2",
	"DirectoryIndex": "keyword2",
	"DocumentRoot": "keyword2",
	"EnableMMAP": "keyword2",
	"EnableSendfile": "keyword2",
	"ErrorDocument": "keyword2",
	"ErrorLog": "keyword2",
	"Example": "keyword2",
	"ExpiresActive": "keyword2",
	"ExpiresByType": "keyword2",
	"ExpiresDefault": "keyword2",
	"ExtFilterDefine": "keyword2",
	"ExtendedStatus": "keyword2",
	"FileETag": "keyword2",
	"ForceLanguagePriority": "keyword2",
	"Group": "keyword2",
	"Header": "keyword2",
	"HeaderName": "keyword2",
	"HostnameLookups": "keyword2",
	"ISAPIAppendLogToErrors": "keyword2",
	"ISAPIAppendLogToQuery": "keyword2",
	"ISAPICacheFile": "keyword2",
	"ISAPIFakeAsync": "keyword2",
	"ISAPILogNotSupported": "keyword2",
	"ISAPIReadAheadBuffer": "keyword2",
	"IdentityCheck": "keyword2",
	"ImapBase": "keyword2",
	"ImapDefault": "keyword2",
	"ImapMenu": "keyword2",
	"Include": "keyword2",
	"IndexIgnore": "keyword2",
	"IndexOptions": "keyword2",
	"IndexOrderDefault": "keyword2",
	"KeepAlive": "keyword2",
	"KeepAliveTimeout": "keyword2",
	"LDAPCacheEntries": "keyword2",
	"LDAPCacheTTL": "keyword2",
	"LDAPOpCacheEntries": "keyword2",
	"LDAPOpCacheTTL": "keyword2",
	"LDAPSharedCacheSize": "keyword2",
	"LDAPTrustedCA": "keyword2",
	"LDAPTrustedCAType": "keyword2",
	"LanguagePriority": "keyword2",
	"LimitInternalRecursion": "keyword2",
	"LimitRequestBody": "keyword2",
	"LimitRequestFields": "keyword2",
	"LimitRequestFieldsize": "keyword2",
	"LimitRequestLine": "keyword2",
	"LimitXMLRequestBody": "keyword2",
	"Listen": "keyword2",
	"ListenBacklog": "keyword2",
	"LoadFile": "keyword2",
	"LoadModule": "keyword2",
	"LockFile": "keyword2",
	"LogFormat": "keyword2",
	"LogLevel": "keyword2",
	"MCacheMaxObjectCount": "keyword2",
	"MCacheMaxObjectSize": "keyword2",
	"MCacheMaxStreamingBuffer": "keyword2",
	"MCacheMinObjectSize": "keyword2",
	"MCacheRemovalAlgorithm": "keyword2",
	"MCacheSize": "keyword2",
	"MMapFile": "keyword2",
	"MaxClients": "keyword2",
	"MaxKeepAliveRequests": "keyword2",
	"MaxMemFree": "keyword2",
	"MaxRequestsPerChild": "keyword2",
	"MaxRequestsPerThread": "keyword2",
	"MaxSpareServers": "keyword2",
	"MaxSpareThreads": "keyword2",
	"MaxThreads": "keyword2",
	"MaxThreadsPerChild": "keyword2",
	"MetaDir": "keyword2",
	"MetaFiles": "keyword2",
	"MetaSuffix": "keyword2",
	"MimeMagicFile": "keyword2",
	"MinSpareServers": "keyword2",
	"MinSpareThreads": "keyword2",
	"MultiviewsMatch": "keyword2",
	"NWSSLTrustedCerts": "keyword2",
	"NameVirtualHost": "keyword2",
	"NoProxy": "keyword2",
	"NumServers": "keyword2",
	"Options": "keyword2",
	"PassEnv": "keyword2",
	"PidFile": "keyword2",
	"ProtocolEcho": "keyword2",
	"ProxyBadHeader": "keyword2",
	"ProxyBlock": "keyword2",
	"ProxyDomain": "keyword2",
	"ProxyErrorOverride": "keyword2",
	"ProxyIOBufferSize": "keyword2",
	"ProxyMaxForwards": "keyword2",
	"ProxyPass": "keyword2",
	"ProxyPassReverse": "keyword2",
	"ProxyPreserveHost": "keyword2",
	"ProxyReceiveBufferSize": "keyword2",
	"ProxyRemote": "keyword2",
	"ProxyRemoteMatch": "keyword2",
	"ProxyRequests": "keyword2",
	"ProxyTimeout": "keyword2",
	"ProxyVia": "keyword2",
	"RLimitCPU": "keyword2",
	"RLimitMEM": "keyword2",
	"RLimitNPROC": "keyword2",
	"ReadmeName": "keyword2",
	"Redirect": "keyword2",
	"RedirectMatch": "keyword2",
	"RedirectPermanent": "keyword2",
	"RedirectTemp": "keyword2",
	"RemoveCharset": "keyword2",
	"RemoveEncoding": "keyword2",
	"RemoveHandler": "keyword2",
	"RemoveInputFilter": "keyword2",
	"RemoveLanguage": "keyword2",
	"RemoveOutputFilter": "keyword2",
	"RemoveType": "keyword2",
	"RequestHeader": "keyword2",
	"RewriteCond": "keyword2",
	"RewriteEngine": "keyword2",
	"RewriteLock": "keyword2",
	"RewriteLog": "keyword2",
	"RewriteLogLevel": "keyword2",
	"RewriteMap": "keyword2",
	"RewriteOptions": "keyword2",
	"RewriteRule": "keyword2",
	"SSIEndTag": "keyword2",
	"SSIErrorMsg": "keyword2",
	"SSIStartTag": "keyword2",
	"SSITimeFormat": "keyword2",
	"SSIUndefinedEcho": "keyword2",
	"SSLCACertificateFile": "keyword2",
	"SSLCACertificatePath": "keyword2",
	"SSLCARevocationFile": "keyword2",
	"SSLCARevocationPath": "keyword2",
	"SSLCertificateChainFile": "keyword2",
	"SSLCertificateFile": "keyword2",
	"SSLCertificateKeyFile": "keyword2",
	"SSLCipherSuite": "keyword2",
	"SSLEngine": "keyword2",
	"SSLMutex": "keyword2",
	"SSLOptions": "keyword2",
	"SSLPassPhraseDialog": "keyword2",
	"SSLProtocol": "keyword2",
	"SSLProxyCACertificateFile": "keyword2",
	"SSLProxyCACertificatePath": "keyword2",
	"SSLProxyCARevocationFile": "keyword2",
	"SSLProxyCARevocationPath": "keyword2",
	"SSLProxyCipherSuite": "keyword2",
	"SSLProxyEngine": "keyword2",
	"SSLProxyMachineCertificateFile": "keyword2",
	"SSLProxyMachineCertificatePath": "keyword2",
	"SSLProxyProtocol": "keyword2",
	"SSLProxyVerify": "keyword2",
	"SSLProxyVerifyDepth": "keyword2",
	"SSLRandomSeed": "keyword2",
	"SSLSessionCache": "keyword2",
	"SSLSessionCacheTimeout": "keyword2",
	"SSLVerifyClient": "keyword2",
	"SSLVerifyDepth": "keyword2",
	"ScoreBoardFile": "keyword2",
	"Script": "keyword2",
	"ScriptAlias": "keyword2",
	"ScriptAliasMatch": "keyword2",
	"ScriptInterpreterSource": "keyword2",
	"ScriptLog": "keyword2",
	"ScriptLogBuffer": "keyword2",
	"ScriptLogLength": "keyword2",
	"ScriptSock": "keyword2",
	"SecureListen": "keyword2",
	"SendBufferSize": "keyword2",
	"ServerAdmin": "keyword2",
	"ServerAlias": "keyword2",
	"ServerLimit": "keyword2",
	"ServerName": "keyword2",
	"ServerPath": "keyword2",
	"ServerRoot": "keyword2",
	"ServerSignature": "keyword2",
	"ServerTokens": "keyword2",
	"SetEnv": "keyword2",
	"SetEnvIf": "keyword2",
	"SetEnvIfNoCase": "keyword2",
	"SetHandler": "keyword2",
	"SetInputFilter": "keyword2",
	"SetOutputFilter": "keyword2",
	"StartServers": "keyword2",
	"StartThreads": "keyword2",
	"SuexecUserGroup": "keyword2",
	"ThreadLimit": "keyword2",
	"ThreadStackSize": "keyword2",
	"ThreadsPerChild": "keyword2",
	"TimeOut": "keyword2",
	"TransferLog": "keyword2",
	"TypesConfig": "keyword2",
	"UnsetEnv": "keyword2",
	"UseCanonicalName": "keyword2",
	"User": "keyword2",
	"UserDir": "keyword2",
	"VirtualDocumentRoot": "keyword2",
	"VirtualDocumentRootIP": "keyword2",
	"VirtualScriptAlias": "keyword2",
	"VirtualScriptAliasIP": "keyword2",
	"XBitHack": "keyword2",
}

# Rules for apacheconf_main ruleset.

def rule0(colorer, s, i):
    return colorer.match_eol_span(s, i, kind='"comment1"', seq="#",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule1(colorer, s, i):
    return colorer.match_span(s, i, kind='"literal1"', begin="\"", end="\"",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule2(colorer, s, i):
    return colorer.match_span_regexp(s, i, kind='"markup"', begin="<(VirtualHost)[^>]*>", end="</$1>",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="VHOST",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule3(colorer, s, i):
    return colorer.match_span_regexp(s, i, kind='"markup"', begin="<(\w+)[^>]*>", end="</$1>",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="DIRECTIVE",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule4(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules list for apacheconf_main ruleset.
apacheconf_main_rules = [
	rule0, rule1, rule2, rule3, rule4, ]

# Rules for apacheconf_directive ruleset.

def rule5(colorer, s, i):
    return colorer.match_eol_span(s, i, kind='"comment2"', seq="#",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule6(colorer, s, i):
    return colorer.match_span(s, i, kind='"literal1"', begin="\"", end="\"",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule7(colorer, s, i):
    return colorer.match_span_regexp(s, i, kind='"markup"', begin="<(VirtualHost)[^>]*>", end="</$1>",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="VHOST",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule8(colorer, s, i):
    return colorer.match_span_regexp(s, i, kind='"markup"', begin="<(\w+)[^>]*>", end="</$1>",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="DIRECTIVE",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule9(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules list for apacheconf_directive ruleset.
apacheconf_directive_rules = [
	rule5, rule6, rule7, rule8, rule9, ]

# Rules for apacheconf_vhost ruleset.

def rule10(colorer, s, i):
    return colorer.match_eol_span(s, i, kind='"comment2"', seq="#",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule11(colorer, s, i):
    return colorer.match_span(s, i, kind='"literal1"', begin="\"", end="\"",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule12(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules list for apacheconf_vhost ruleset.
apacheconf_vhost_rules = [
	rule10, rule11, rule12, ]

# Rules dict for apacheconf mode.
rulesDict = {
	"apacheconf_directive": apacheconf_directive_rules,
	"apacheconf_main": apacheconf_main_rules,
	"apacheconf_vhost": apacheconf_vhost_rules,
}

# Import dict for apacheconf mode.
importDict = {}

