# Leo colorizer control file for assembly-r2000 mode.

# Properties for assembly-r2000 mode.
properties = {
	"blockComment": "#",
	"wordBreakChars": ",()",
}

# Keywords dict for assembly_r2000_main ruleset.
assembly_r2000_main_keywords_dict = {
	"$a0": "keyword2",
	"$a1": "keyword2",
	"$a2": "keyword2",
	"$a3": "keyword2",
	"$at": "keyword2",
	"$f0": "keyword3",
	"$f1": "keyword3",
	"$f10": "keyword3",
	"$f11": "keyword3",
	"$f12": "keyword3",
	"$f13": "keyword3",
	"$f14": "keyword3",
	"$f15": "keyword3",
	"$f16": "keyword3",
	"$f17": "keyword3",
	"$f18": "keyword3",
	"$f19": "keyword3",
	"$f2": "keyword3",
	"$f20": "keyword3",
	"$f21": "keyword3",
	"$f22": "keyword3",
	"$f23": "keyword3",
	"$f24": "keyword3",
	"$f25": "keyword3",
	"$f26": "keyword3",
	"$f27": "keyword3",
	"$f28": "keyword3",
	"$f29": "keyword3",
	"$f3": "keyword3",
	"$f30": "keyword3",
	"$f31": "keyword3",
	"$f4": "keyword3",
	"$f5": "keyword3",
	"$f6": "keyword3",
	"$f7": "keyword3",
	"$f8": "keyword3",
	"$f9": "keyword3",
	"$fp": "keyword2",
	"$k0": "keyword2",
	"$k1": "keyword2",
	"$ra": "keyword2",
	"$s0": "keyword2",
	"$s1": "keyword2",
	"$s2": "keyword2",
	"$s3": "keyword2",
	"$s4": "keyword2",
	"$s5": "keyword2",
	"$s6": "keyword2",
	"$s7": "keyword2",
	"$sp": "keyword2",
	"$t1": "keyword2",
	"$t2": "keyword2",
	"$t3": "keyword2",
	"$t4": "keyword2",
	"$t5": "keyword2",
	"$t6": "keyword2",
	"$t7": "keyword2",
	"$t8": "keyword2",
	"$t9": "keyword2",
	"$v0": "keyword2",
	"$v1": "keyword2",
	"$zero": "keyword2",
	".align": "keyword1",
	".ascii": "keyword1",
	".asciiz": "keyword1",
	".byte": "keyword1",
	".data": "keyword1",
	".double": "keyword1",
	".extern": "keyword1",
	".float": "keyword1",
	".globl": "keyword1",
	".half": "keyword1",
	".kdata": "keyword1",
	".ktext": "keyword1",
	".space": "keyword1",
	".text": "keyword1",
	".word": "keyword1",
	"abs.d": "function",
	"abs.s": "function",
	"add": "function",
	"add.d": "function",
	"add.s": "function",
	"addi": "function",
	"addiu": "function",
	"addu": "function",
	"and": "function",
	"andi": "function",
	"b": "function",
	"bczf": "function",
	"bczt": "function",
	"beq": "function",
	"beqz": "function",
	"bge": "function",
	"bgeu": "function",
	"bgez": "function",
	"bgezal": "function",
	"bgt": "function",
	"bgtu": "function",
	"bgtz": "function",
	"ble": "function",
	"bleu": "function",
	"blez": "function",
	"blt": "function",
	"bltu": "function",
	"bltz": "function",
	"bltzal": "function",
	"blu": "function",
	"bne": "function",
	"bnez": "function",
	"break": "function",
	"c.eq.d": "function",
	"c.eq.s": "function",
	"c.le.d": "function",
	"c.le.s": "function",
	"c.lt.d": "function",
	"c.lt.s": "function",
	"cbt.d.w": "function",
	"cvt.d.s": "function",
	"cvt.s.d": "function",
	"cvt.s.w": "function",
	"cvt.w.d": "function",
	"cvt.w.s": "function",
	"div": "function",
	"div.d": "function",
	"div.s": "function",
	"divu": "function",
	"j": "function",
	"jal": "function",
	"jalr": "function",
	"jr": "function",
	"l.d": "function",
	"l.s": "function",
	"la": "function",
	"lb": "function",
	"lh": "function",
	"lhu": "function",
	"li": "function",
	"lui": "function",
	"lw": "function",
	"lwcz": "function",
	"lwl": "function",
	"lwr": "function",
	"mfc1.d": "function",
	"mfcz": "function",
	"mfhi": "function",
	"mflo": "function",
	"mov.d": "function",
	"mov.s": "function",
	"move": "function",
	"mtcz": "function",
	"mthi": "function",
	"mtlo": "function",
	"mul": "function",
	"mul.d": "function",
	"mul.s": "function",
	"mulo": "function",
	"mulou": "function",
	"mult": "function",
	"multu": "function",
	"neg": "function",
	"neg.d": "function",
	"neg.s": "function",
	"negu": "function",
	"nop": "function",
	"nor": "function",
	"not": "function",
	"or": "function",
	"ori": "function",
	"rem": "function",
	"remu": "function",
	"rfe": "function",
	"rol": "function",
	"ror": "function",
	"s.d": "function",
	"s.s": "function",
	"sb": "function",
	"sd": "function",
	"seq": "function",
	"sge": "function",
	"sgt": "function",
	"sgtu": "function",
	"sh": "function",
	"sle": "function",
	"sleu": "function",
	"sll": "function",
	"sllv": "function",
	"slt": "function",
	"slti": "function",
	"sltiu": "function",
	"sltu": "function",
	"sne": "function",
	"sra": "function",
	"srav": "function",
	"srl": "function",
	"srlv": "function",
	"sub": "function",
	"sub.d": "function",
	"sub.s": "function",
	"subu": "function",
	"sw": "function",
	"swcz": "function",
	"swl": "function",
	"swr": "function",
	"syscall": "function",
	"ulh": "function",
	"ulhu": "function",
	"ulw": "function",
	"ush": "function",
	"usw": "function",
	"xor": "function",
	"xori": "function",
}

# Rules for assembly_r2000_main ruleset.

def rule0(colorer, s, i):
    return colorer.match_eol_span(s, i, kind='"comment1"', seq="#",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule1(colorer, s, i):
    return colorer.match_span(s, i, kind='"literal1"', begin="'", end="'",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule2(colorer, s, i):
    return colorer.match_span(s, i, kind='"literal1"', begin="\"", end="\"",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule3(colorer, s, i):
    return colorer.match_mark_previous(s, i, kind='"label"',
        at_line_start=True, at_line_end=False, at_word_start=False, exclude_match=False)

def rule4(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules list for assembly_r2000_main ruleset.
assembly_r2000_main_rules = [
	rule0, rule1, rule2, rule3, rule4, ]

# Rules dict for assembly_r2000 mode.
rulesDict = {
	"assembly_r2000_main": assembly_r2000_main_rules,
}

# Import dict for assembly_r2000 mode.
importDict = {}

