# Leo colorizer control file for assembly-r2000 mode.

# Properties for assembly-r2000 mode.
properties = {
	"blockComment": "#",
	"wordBreakChars": ",()",
}

# Keywords dict for assembly_r2000_main ruleset.
assembly_r2000_main_keywords_dict = {
	"		": "keywords",
	"			": "keywords",
	"
": "keywords",
	"$a0": "keyword2",
	"$a1": "keyword2",
	"$a2": "keyword2",
	"$a3": "keyword2",
	"$at": "keyword2",
	"$f0": "keyword3",
	"$f1": "keyword3",
	"$f10": "keyword3",
	"$f11": "keyword3",
	"$f12": "keyword3",
	"$f13": "keyword3",
	"$f14": "keyword3",
	"$f15": "keyword3",
	"$f16": "keyword3",
	"$f17": "keyword3",
	"$f18": "keyword3",
	"$f19": "keyword3",
	"$f2": "keyword3",
	"$f20": "keyword3",
	"$f21": "keyword3",
	"$f22": "keyword3",
	"$f23": "keyword3",
	"$f24": "keyword3",
	"$f25": "keyword3",
	"$f26": "keyword3",
	"$f27": "keyword3",
	"$f28": "keyword3",
	"$f29": "keyword3",
	"$f3": "keyword3",
	"$f30": "keyword3",
	"$f31": "keyword3",
	"$f4": "keyword3",
	"$f5": "keyword3",
	"$f6": "keyword3",
	"$f7": "keyword3",
	"$f8": "keyword3",
	"$f9": "keyword3",
	"$fp": "keyword2",
	"$k0": "keyword2",
	"$k1": "keyword2",
	"$ra": "keyword2",
	"$s0": "keyword2",
	"$s1": "keyword2",
	"$s2": "keyword2",
	"$s3": "keyword2",
	"$s4": "keyword2",
	"$s5": "keyword2",
	"$s6": "keyword2",
	"$s7": "keyword2",
	"$sp": "keyword2",
	"$t1": "keyword2",
	"$t2": "keyword2",
	"$t3": "keyword2",
	"$t4": "keyword2",
	"$t5": "keyword2",
	"$t6": "keyword2",
	"$t7": "keyword2",
	"$t8": "keyword2",
	"$t9": "keyword2",
	"$v0": "keyword2",
	"$v1": "keyword2",
	"$zero": "keyword2",
	".align": "keyword1",
	".ascii": "keyword1",
	".asciiz": "keyword1",
	".byte": "keyword1",
	".data": "keyword1",
	".double": "keyword1",
	".extern": "keyword1",
	".float": "keyword1",
	".globl": "keyword1",
	".half": "keyword1",
	".kdata": "keyword1",
	".ktext": "keyword1",
	".space": "keyword1",
	".text": "keyword1",
	".word": "keyword1",
	"abs.d": "function",
	"abs.s": "function",
	"add": "function",
	"add.d": "function",
	"add.s": "function",
	"addi": "function",
	"addiu": "function",
	"addu": "function",
	"and": "function",
	"andi": "function",
	"b": "function",
	"bczf": "function",
	"bczt": "function",
	"beq": "function",
	"beqz": "function",
	"bge": "function",
	"bgeu": "function",
	"bgez": "function",
	"bgezal": "function",
	"bgt": "function",
	"bgtu": "function",
	"bgtz": "function",
	"ble": "function",
	"bleu": "function",
	"blez": "function",
	"blt": "function",
	"bltu": "function",
	"bltz": "function",
	"bltzal": "function",
	"blu": "function",
	"bne": "function",
	"bnez": "function",
	"break": "function",
	"c.eq.d": "function",
	"c.eq.s": "function",
	"c.le.d": "function",
	"c.le.s": "function",
	"c.lt.d": "function",
	"c.lt.s": "function",
	"cbt.d.w": "function",
	"cvt.d.s": "function",
	"cvt.s.d": "function",
	"cvt.s.w": "function",
	"cvt.w.d": "function",
	"cvt.w.s": "function",
	"div": "function",
	"div.d": "function",
	"div.s": "function",
	"divu": "function",
	"j": "function",
	"jal": "function",
	"jalr": "function",
	"jr": "function",
	"l.d": "function",
	"l.s": "function",
	"la": "function",
	"lb": "function",
	"lh": "function",
	"lhu": "function",
	"li": "function",
	"lui": "function",
	"lw": "function",
	"lwcz": "function",
	"lwl": "function",
	"lwr": "function",
	"mfc1.d": "function",
	"mfcz": "function",
	"mfhi": "function",
	"mflo": "function",
	"mov.d": "function",
	"mov.s": "function",
	"move": "function",
	"mtcz": "function",
	"mthi": "function",
	"mtlo": "function",
	"mul": "function",
	"mul.d": "function",
	"mul.s": "function",
	"mulo": "function",
	"mulou": "function",
	"mult": "function",
	"multu": "function",
	"neg": "function",
	"neg.d": "function",
	"neg.s": "function",
	"negu": "function",
	"nop": "function",
	"nor": "function",
	"not": "function",
	"or": "function",
	"ori": "function",
	"rem": "function",
	"remu": "function",
	"rfe": "function",
	"rol": "function",
	"ror": "function",
	"s.d": "function",
	"s.s": "function",
	"sb": "function",
	"sd": "function",
	"seq": "function",
	"sge": "function",
	"sgt": "function",
	"sgtu": "function",
	"sh": "function",
	"sle": "function",
	"sleu": "function",
	"sll": "function",
	"sllv": "function",
	"slt": "function",
	"slti": "function",
	"sltiu": "function",
	"sltu": "function",
	"sne": "function",
	"sra": "function",
	"srav": "function",
	"srl": "function",
	"srlv": "function",
	"sub": "function",
	"sub.d": "function",
	"sub.s": "function",
	"subu": "function",
	"sw": "function",
	"swcz": "function",
	"swl": "function",
	"swr": "function",
	"syscall": "function",
	"ulh": "function",
	"ulhu": "function",
	"ulw": "function",
	"ush": "function",
	"usw": "function",
	"xor": "function",
	"xori": "function",
}

# Dictionary of keywords dictionaries for assembly_r2000 mode.
keywordsDictDict = {
	"assembly_r2000_main": assembly_r2000_main_keywords_dict,
}

# Rules for assembly_r2000_main ruleset.

def rule0(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment1", seq="#",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule1(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="'", end="'",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule2(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="\"", end="\"",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule3(colorer, s, i):
    return colorer.match_mark_previous(s, i, kind="label", pattern=":",
        at_line_start=True, at_whitespace_end=False, at_word_start=False, exclude_match=False)

def rule4(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules dict for main ruleset.
rulesDict1 = {
	"\"": [rule2,],
	"#": [rule0,],
	"'": [rule1,],
	"0": [rule4,],
	"1": [rule4,],
	"2": [rule4,],
	"3": [rule4,],
	"4": [rule4,],
	"5": [rule4,],
	"6": [rule4,],
	"7": [rule4,],
	"8": [rule4,],
	"9": [rule4,],
	":": [rule3,],
	"@": [rule4,],
	"A": [rule4,],
	"B": [rule4,],
	"C": [rule4,],
	"D": [rule4,],
	"E": [rule4,],
	"F": [rule4,],
	"G": [rule4,],
	"H": [rule4,],
	"I": [rule4,],
	"J": [rule4,],
	"K": [rule4,],
	"L": [rule4,],
	"M": [rule4,],
	"N": [rule4,],
	"O": [rule4,],
	"P": [rule4,],
	"Q": [rule4,],
	"R": [rule4,],
	"S": [rule4,],
	"T": [rule4,],
	"U": [rule4,],
	"V": [rule4,],
	"W": [rule4,],
	"X": [rule4,],
	"Y": [rule4,],
	"Z": [rule4,],
	"_": [rule4,],
	"a": [rule4,],
	"b": [rule4,],
	"c": [rule4,],
	"d": [rule4,],
	"e": [rule4,],
	"f": [rule4,],
	"g": [rule4,],
	"h": [rule4,],
	"i": [rule4,],
	"j": [rule4,],
	"k": [rule4,],
	"l": [rule4,],
	"m": [rule4,],
	"n": [rule4,],
	"o": [rule4,],
	"p": [rule4,],
	"q": [rule4,],
	"r": [rule4,],
	"s": [rule4,],
	"t": [rule4,],
	"u": [rule4,],
	"v": [rule4,],
	"w": [rule4,],
	"x": [rule4,],
	"y": [rule4,],
	"z": [rule4,],
}

# x.rulesDictDict for assembly_r2000 mode.
rulesDictDict = {
	"assembly_r2000_main": rulesDict1,
}

# Import dict for assembly_r2000 mode.
importDict = {}

