# Leo colorizer control file for cobol mode.
# This file is in the public domain.

# Properties for cobol mode.
properties = {
	"lineComment": "*",
}

# Attributes dict for cobol_main ruleset.
cobol_main_attributes_dict = {
	"default": "null",
	"digit_re": "",
	"highlight_digits": "true",
	"ignore_case": "true",
	"no_word_sep": "",
}

# Dictionary of attributes dictionaries for cobol mode.
attributesDictDict = {
	"cobol_main": cobol_main_attributes_dict,
}

# Keywords dict for cobol_main ruleset.
cobol_main_keywords_dict = {
	"ACCEPT": "keyword1",
	"ACCESS": "keyword1",
	"ACOS": "keyword2",
	"ACTUAL": "keyword1",
	"ADD": "keyword1",
	"ADDRESS": "keyword1",
	"ADVANCING": "keyword1",
	"AFTER": "keyword1",
	"ALL": "keyword1",
	"ALPHABET": "keyword1",
	"ALPHABETIC": "keyword1",
	"ALPHABETIC-LOWER": "keyword1",
	"ALPHABETIC-UPPER": "keyword1",
	"ALPHANUMERIC": "keyword1",
	"ALPHANUMERIC-EDITED": "keyword1",
	"ALSO": "keyword1",
	"ALTER": "keyword1",
	"ALTERNATE": "keyword1",
	"AND": "keyword1",
	"ANNUITY": "keyword2",
	"ANY": "keyword1",
	"API": "keyword1",
	"APPLY": "keyword1",
	"ARE": "keyword1",
	"AREA": "keyword1",
	"AREAS": "keyword1",
	"ASCENDING": "keyword1",
	"ASIN": "keyword2",
	"ASSIGN": "keyword1",
	"AT": "keyword1",
	"ATAN": "keyword2",
	"AUTHOR": "keyword1",
	"AUTO": "keyword1",
	"AUTO-SKIP": "keyword1",
	"AUTOMATIC": "keyword1",
	"BACKGROUND-COLOR": "keyword1",
	"BACKGROUND-COLOUR": "keyword1",
	"BACKWARD": "keyword1",
	"BASIS": "keyword1",
	"BEEP": "keyword1",
	"BEFORE": "keyword1",
	"BEGINNING": "keyword1",
	"BELL": "keyword1",
	"BINARY": "keyword1",
	"BLANK": "keyword1",
	"BLINK": "keyword1",
	"BLOCK": "keyword1",
	"BOTTOM": "keyword1",
	"BY": "keyword1",
	"C01": "keyword1",
	"C02": "keyword1",
	"C03": "keyword1",
	"C04": "keyword1",
	"C05": "keyword1",
	"C06": "keyword1",
	"C07": "keyword1",
	"C08": "keyword1",
	"C09": "keyword1",
	"C10": "keyword1",
	"C11": "keyword1",
	"C12": "keyword1",
	"CALL": "keyword1",
	"CALL-CONVENTION": "keyword1",
	"CANCEL": "keyword1",
	"CBL": "keyword1",
	"CD": "keyword1",
	"CF": "keyword1",
	"CH": "keyword1",
	"CHAIN": "keyword1",
	"CHAINING": "keyword1",
	"CHANGED": "keyword1",
	"CHAR": "keyword2",
	"CHARACTER": "keyword1",
	"CHARACTERS": "keyword1",
	"CLASS": "keyword1",
	"CLOCK-UNITS": "keyword1",
	"CLOSE": "keyword1",
	"COBOL": "keyword1",
	"CODE": "keyword1",
	"CODE-SET": "keyword1",
	"COL": "keyword1",
	"COLLATING": "keyword1",
	"COLUMN": "keyword1",
	"COM-REG": "keyword1",
	"COMMA": "keyword1",
	"COMMIT": "keyword1",
	"COMMON": "keyword1",
	"COMMUNICATION": "keyword1",
	"COMP": "keyword1",
	"COMP-0": "keyword1",
	"COMP-1": "keyword1",
	"COMP-2": "keyword1",
	"COMP-3": "keyword1",
	"COMP-4": "keyword1",
	"COMP-5": "keyword1",
	"COMP-6": "keyword1",
	"COMP-X": "keyword1",
	"COMPUTATIONAL": "keyword1",
	"COMPUTATIONAL-0": "keyword1",
	"COMPUTATIONAL-1": "keyword1",
	"COMPUTATIONAL-2": "keyword1",
	"COMPUTATIONAL-3": "keyword1",
	"COMPUTATIONAL-4": "keyword1",
	"COMPUTATIONAL-5": "keyword1",
	"COMPUTATIONAL-6": "keyword1",
	"COMPUTATIONAL-X": "keyword1",
	"COMPUTE": "keyword1",
	"CONFIGURATION": "keyword1",
	"CONSOLE": "keyword1",
	"CONTAINS": "keyword1",
	"CONTENT": "keyword1",
	"CONTINUE": "keyword1",
	"CONTROL": "keyword1",
	"CONTROLS": "keyword1",
	"CONVERTING": "keyword1",
	"COPY": "keyword1",
	"CORE-INDEX": "keyword1",
	"CORR": "keyword1",
	"CORRESPONDING": "keyword1",
	"COS": "keyword2",
	"COUNT": "keyword1",
	"CRT": "keyword1",
	"CRT-UNDER": "keyword1",
	"CURRENCY": "keyword1",
	"CURRENT-DATE": "keyword2",
	"CURSOR": "keyword1",
	"CYCLE": "keyword1",
	"CYL-INDEX": "keyword1",
	"CYL-OVERFLOW": "keyword1",
	"DATA": "keyword1",
	"DATE": "keyword1",
	"DATE-COMPILED": "keyword1",
	"DATE-OF-INTEGER": "keyword2",
	"DATE-WRITTEN": "keyword1",
	"DAY": "keyword1",
	"DAY-OF-INTEGER": "keyword2",
	"DAY-OF-WEEK": "keyword1",
	"DBCS": "keyword1",
	"DE": "keyword1",
	"DEBUG": "keyword1",
	"DEBUG-CONTENTS": "keyword1",
	"DEBUG-ITEM": "keyword1",
	"DEBUG-LINE": "keyword1",
	"DEBUG-NAME": "keyword1",
	"DEBUG-SUB-1": "keyword1",
	"DEBUG-SUB-2": "keyword1",
	"DEBUG-SUB-3": "keyword1",
	"DEBUGGING": "keyword1",
	"DECIMAL-POINT": "keyword1",
	"DECLARATIVES": "keyword1",
	"DELETE": "keyword1",
	"DELIMITED": "keyword1",
	"DELIMITER": "keyword1",
	"DEPENDING": "keyword1",
	"DESCENDING": "keyword1",
	"DESTINATION": "keyword1",
	"DETAIL": "keyword1",
	"DISABLE": "keyword1",
	"DISK": "keyword1",
	"DISP": "keyword1",
	"DISPLAY": "keyword1",
	"DISPLAY-1": "keyword1",
	"DISPLAY-ST": "keyword1",
	"DIVIDE": "keyword1",
	"DIVISION": "keyword1",
	"DOWN": "keyword1",
	"DUPLICATES": "keyword1",
	"DYNAMIC": "keyword1",
	"ECHO": "keyword1",
	"EGCS": "keyword1",
	"EGI": "keyword1",
	"EJECT": "keyword1",
	"ELSE": "keyword1",
	"EMI": "keyword1",
	"EMPTY-CHECK": "keyword1",
	"ENABLE": "keyword1",
	"END": "keyword1",
	"END-ACCEPT": "keyword1",
	"END-ADD": "keyword1",
	"END-CALL": "keyword1",
	"END-CHAIN": "keyword1",
	"END-COMPUTE": "keyword1",
	"END-DELETE": "keyword1",
	"END-DISPLAY": "keyword1",
	"END-DIVIDE": "keyword1",
	"END-EVALUATE": "keyword1",
	"END-IF": "keyword1",
	"END-INVOKE": "keyword1",
	"END-MULTIPLY": "keyword1",
	"END-OF-PAGE": "keyword1",
	"END-PERFORM": "keyword1",
	"END-READ": "keyword1",
	"END-RECEIVE": "keyword1",
	"END-RETURN": "keyword1",
	"END-REWRITE": "keyword1",
	"END-SEARCH": "keyword1",
	"END-START": "keyword1",
	"END-STRING": "keyword1",
	"END-SUBTRACT": "keyword1",
	"END-UNSTRING": "keyword1",
	"END-WRITE": "keyword1",
	"ENDING": "keyword1",
	"ENTER": "keyword1",
	"ENTRY": "keyword1",
	"ENVIRONMENT": "keyword1",
	"EOL": "keyword1",
	"EOP": "keyword1",
	"EOS": "keyword1",
	"EQUAL": "keyword1",
	"EQUALS": "keyword1",
	"ERASE": "keyword1",
	"ERROR": "keyword1",
	"ESCAPE": "keyword1",
	"ESI": "keyword1",
	"EVALUATE": "keyword1",
	"EVERY": "keyword1",
	"EXAMINE": "keyword1",
	"EXCEEDS": "keyword1",
	"EXCEPTION": "keyword1",
	"EXCESS-3": "keyword1",
	"EXCLUSIVE": "keyword1",
	"EXEC": "keyword1",
	"EXECUTE": "keyword1",
	"EXHIBIT": "keyword1",
	"EXIT": "keyword1",
	"EXTEND": "keyword1",
	"EXTENDED-SEARCH": "keyword1",
	"EXTERNAL": "keyword1",
	"FACTORIAL": "keyword2",
	"FACTORY": "keyword1",
	"FALSE": "keyword1",
	"FD": "keyword1",
	"FH-FCD": "keyword1",
	"FH-KEYDEF": "keyword1",
	"FILE": "keyword1",
	"FILE-CONTROL": "keyword1",
	"FILE-ID": "keyword1",
	"FILE-LIMIT": "keyword1",
	"FILE-LIMITS": "keyword1",
	"FILLER": "keyword1",
	"FINAL": "keyword1",
	"FIRST": "keyword1",
	"FIXED": "keyword1",
	"FOOTING": "keyword1",
	"FOR": "keyword1",
	"FOREGROUND-COLOR": "keyword1",
	"FOREGROUND-COLOUR": "keyword1",
	"FROM": "keyword1",
	"FULL": "keyword1",
	"FUNCTION": "keyword1",
	"GENERATE": "keyword1",
	"GIVING": "keyword1",
	"GLOBAL": "keyword1",
	"GO": "keyword1",
	"GOBACK": "keyword1",
	"GREATER": "keyword1",
	"GRID": "keyword1",
	"GROUP": "keyword1",
	"HEADING": "keyword1",
	"HIGH": "keyword1",
	"HIGH-VALUE": "keyword1",
	"HIGH-VALUES": "keyword1",
	"HIGHLIGHT": "keyword1",
	"I-O": "keyword1",
	"I-O-CONTROL": "keyword1",
	"ID": "keyword1",
	"IDENTIFICATION": "keyword1",
	"IF": "keyword1",
	"IGNORE": "keyword1",
	"IN": "keyword1",
	"INDEX": "keyword1",
	"INDEXED": "keyword1",
	"INDICATE": "keyword1",
	"INHERITING": "keyword1",
	"INITIAL": "keyword1",
	"INITIALIZE": "keyword1",
	"INITIATE": "keyword1",
	"INPUT": "keyword1",
	"INPUT-OUTPUT": "keyword1",
	"INSERT": "keyword1",
	"INSPECT": "keyword1",
	"INSTALLATION": "keyword1",
	"INTEGER": "keyword2",
	"INTEGER-OF-DATE": "keyword2",
	"INTEGER-OF-DAY": "keyword2",
	"INTEGER-PART": "keyword2",
	"INTO": "keyword1",
	"INVALID": "keyword1",
	"INVOKE": "keyword1",
	"IS": "keyword1",
	"JAPANESE": "keyword1",
	"JUST": "keyword1",
	"JUSTIFIED": "keyword1",
	"KANJI": "keyword1",
	"KEPT": "keyword1",
	"KEY": "keyword1",
	"KEYBOARD": "keyword1",
	"LABEL": "keyword1",
	"LAST": "keyword1",
	"LEADING": "keyword1",
	"LEAVE": "keyword1",
	"LEFT": "keyword1",
	"LEFT-JUSTIFY": "keyword1",
	"LEFTLINE": "keyword1",
	"LENGTH": "keyword1",
	"LENGTH-CHECK": "keyword1",
	"LESS": "keyword1",
	"LIMIT": "keyword1",
	"LIMITS": "keyword1",
	"LIN": "keyword1",
	"LINAGE": "keyword1",
	"LINAGE-COUNTER": "keyword1",
	"LINE": "keyword1",
	"LINE-COUNTER": "keyword1",
	"LINES": "keyword1",
	"LINKAGE": "keyword1",
	"LOCAL-STORAGE": "keyword1",
	"LOCK": "keyword1",
	"LOCKING": "keyword1",
	"LOG": "keyword2",
	"LOG10": "keyword2",
	"LOW": "keyword1",
	"LOW-VALUE": "keyword1",
	"LOW-VALUES": "keyword1",
	"LOWER": "keyword1",
	"LOWER-CASE": "keyword2",
	"LOWLIGHT": "keyword1",
	"MANUAL": "keyword1",
	"MASTER-INDEX": "keyword1",
	"MAX": "keyword2",
	"MEAN": "keyword2",
	"MEDIAN": "keyword2",
	"MEMORY": "keyword1",
	"MERGE": "keyword1",
	"MESSAGE": "keyword1",
	"METHOD": "keyword1",
	"MIDRANGE": "keyword2",
	"MIN": "keyword2",
	"MOD": "keyword2",
	"MODE": "keyword1",
	"MODULES": "keyword1",
	"MORE-LABELS": "keyword1",
	"MOVE": "keyword1",
	"MULTIPLE": "keyword1",
	"MULTIPLY": "keyword1",
	"NAME": "keyword1",
	"NAMED": "keyword1",
	"NATIONAL": "keyword1",
	"NATIONAL-EDITED": "keyword1",
	"NATIVE": "keyword1",
	"NCHAR": "keyword1",
	"NEGATIVE": "keyword1",
	"NEXT": "keyword1",
	"NO": "keyword1",
	"NO-ECHO": "keyword1",
	"NOMINAL": "keyword1",
	"NOT": "keyword1",
	"NOTE": "keyword1",
	"NSTD-REELS": "keyword1",
	"NULL": "keyword1",
	"NULLS": "keyword1",
	"NUMBER": "keyword1",
	"NUMERIC": "keyword1",
	"NUMERIC-EDITED": "keyword1",
	"NUMVAL": "keyword2",
	"NUMVAL-C": "keyword2",
	"OBJECT": "keyword1",
	"OBJECT-COMPUTER": "keyword1",
	"OBJECT-STORAGE": "keyword1",
	"OCCURS": "keyword1",
	"OF": "keyword1",
	"OFF": "keyword1",
	"OMITTED": "keyword1",
	"ON": "keyword1",
	"OOSTACKPTR": "keyword1",
	"OPEN": "keyword1",
	"OPTIONAL": "keyword1",
	"OR": "keyword1",
	"ORD": "keyword2",
	"ORD-MAX": "keyword2",
	"ORD-MIN": "keyword2",
	"ORDER": "keyword1",
	"ORGANIZATION": "keyword1",
	"OTHER": "keyword1",
	"OTHERWISE": "keyword1",
	"OUTPUT": "keyword1",
	"OVERFLOW": "keyword1",
	"OVERLINE": "keyword1",
	"PACKED-DECIMAL": "keyword1",
	"PADDING": "keyword1",
	"PAGE": "keyword1",
	"PAGE-COUNTER": "keyword1",
	"PARAGRAPH": "keyword1",
	"PASSWORD": "keyword1",
	"PERFORM": "keyword1",
	"PF": "keyword1",
	"PH": "keyword1",
	"PIC": "keyword1",
	"PICTURE": "keyword1",
	"PLUS": "keyword1",
	"POINTER": "keyword1",
	"POS": "keyword1",
	"POSITION": "keyword1",
	"POSITIONING": "keyword1",
	"POSITIVE": "keyword1",
	"PRESENT-VALUE": "keyword2",
	"PREVIOUS": "keyword1",
	"PRINT": "keyword1",
	"PRINT-SWITCH": "keyword1",
	"PRINTER": "keyword1",
	"PRINTER-1": "keyword1",
	"PRINTING": "keyword1",
	"PRIVATE": "keyword1",
	"PROCEDURE": "keyword1",
	"PROCEDURE-POINTER": "keyword1",
	"PROCEDURES": "keyword1",
	"PROCEED": "keyword1",
	"PROCESSING": "keyword1",
	"PROGRAM": "keyword1",
	"PROGRAM-ID": "keyword1",
	"PROMPT": "keyword1",
	"PROTECTED": "keyword1",
	"PUBLIC": "keyword1",
	"PURGE": "keyword1",
	"QUEUE": "keyword1",
	"QUOTE": "keyword1",
	"QUOTES": "keyword1",
	"RANDOM": "keyword2",
	"RANGE": "keyword2",
	"RD": "keyword1",
	"READ": "keyword1",
	"READY": "keyword1",
	"RECEIVE": "keyword1",
	"RECORD": "keyword1",
	"RECORD-OVERFLOW": "keyword1",
	"RECORDING": "keyword1",
	"RECORDS": "keyword1",
	"REDEFINES": "keyword1",
	"REEL": "keyword1",
	"REFERENCE": "keyword1",
	"REFERENCES": "keyword1",
	"RELATIVE": "keyword1",
	"RELEASE": "keyword1",
	"RELOAD": "keyword1",
	"REM": "keyword2",
	"REMAINDER": "keyword1",
	"REMARKS": "keyword1",
	"REMOVAL": "keyword1",
	"RENAMES": "keyword1",
	"REORG-CRITERIA": "keyword1",
	"REPLACE": "keyword1",
	"REPLACING": "keyword1",
	"REPORT": "keyword1",
	"REPORTING": "keyword1",
	"REPORTS": "keyword1",
	"REQUIRED": "keyword1",
	"REREAD": "keyword1",
	"RERUN": "keyword1",
	"RESERVE": "keyword1",
	"RESET": "keyword1",
	"RETURN": "keyword1",
	"RETURN-CODE": "keyword1",
	"RETURNING": "keyword1",
	"REVERSE": "keyword2",
	"REVERSE-VIDEO": "keyword1",
	"REVERSED": "keyword1",
	"REWIND": "keyword1",
	"REWRITE": "keyword1",
	"RF": "keyword1",
	"RH": "keyword1",
	"RIGHT": "keyword1",
	"RIGHT-JUSTIFY": "keyword1",
	"ROLLBACK": "keyword1",
	"ROUNDED": "keyword1",
	"RUN": "keyword1",
	"S01": "keyword1",
	"S02": "keyword1",
	"S03": "keyword1",
	"S04": "keyword1",
	"S05": "keyword1",
	"SAME": "keyword1",
	"SCREEN": "keyword1",
	"SD": "keyword1",
	"SEARCH": "keyword1",
	"SECTION": "keyword1",
	"SECURE": "keyword1",
	"SECURITY": "keyword1",
	"SEEK": "keyword1",
	"SEGMENT": "keyword1",
	"SEGMENT-LIMIT": "keyword1",
	"SELECT": "keyword1",
	"SELECTIVE": "keyword1",
	"SEND": "keyword1",
	"SENTENCE": "keyword1",
	"SEPARATE": "keyword1",
	"SEQUENCE": "keyword1",
	"SEQUENTIAL": "keyword1",
	"SERVICE": "keyword1",
	"SET": "keyword1",
	"SHIFT-IN": "keyword1",
	"SHIFT-OUT": "keyword1",
	"SIGN": "keyword1",
	"SIN": "keyword2",
	"SIZE": "keyword1",
	"SKIP1": "keyword1",
	"SKIP2": "keyword1",
	"SKIP3": "keyword1",
	"SORT": "keyword1",
	"SORT-CONTROL": "keyword1",
	"SORT-CORE-SIZE": "keyword1",
	"SORT-FILE-SIZE": "keyword1",
	"SORT-MERGE": "keyword1",
	"SORT-MESSAGE": "keyword1",
	"SORT-MODE-SIZE": "keyword1",
	"SORT-OPTION": "keyword1",
	"SORT-RETURN": "keyword1",
	"SOURCE": "keyword1",
	"SOURCE-COMPUTER": "keyword1",
	"SPACE": "keyword1",
	"SPACE-FILL": "keyword1",
	"SPACES": "keyword1",
	"SPECIAL-NAMES": "keyword1",
	"SQRT": "keyword2",
	"STANDARD": "keyword1",
	"STANDARD-1": "keyword1",
	"STANDARD-2": "keyword1",
	"STANDARD-DEVIATION": "keyword2",
	"START": "keyword1",
	"STATUS": "keyword1",
	"STOP": "keyword1",
	"STORE": "keyword1",
	"STRING": "keyword1",
	"SUB-QUEUE-1": "keyword1",
	"SUB-QUEUE-2": "keyword1",
	"SUB-QUEUE-3": "keyword1",
	"SUBTRACT": "keyword1",
	"SUM": "keyword2",
	"SUPER": "keyword1",
	"SUPPRESS": "keyword1",
	"SYMBOLIC": "keyword1",
	"SYNC": "keyword1",
	"SYNCHRONIZED": "keyword1",
	"SYSIN": "keyword1",
	"SYSIPT": "keyword1",
	"SYSLST": "keyword1",
	"SYSOUT": "keyword1",
	"SYSPCH": "keyword1",
	"SYSPUNCH": "keyword1",
	"TAB": "keyword1",
	"TABLE": "keyword1",
	"TALLY": "keyword1",
	"TALLYING": "keyword1",
	"TAN": "keyword2",
	"TAPE": "keyword1",
	"TERMINAL": "keyword1",
	"TERMINATE": "keyword1",
	"TEST": "keyword1",
	"TEXT": "keyword1",
	"THAN": "keyword1",
	"THEN": "keyword1",
	"THROUGH": "keyword1",
	"THRU": "keyword1",
	"TIME": "keyword1",
	"TIME-OF-DAY": "keyword1",
	"TIME-OUT": "keyword1",
	"TIMEOUT": "keyword1",
	"TIMES": "keyword1",
	"TITLE": "keyword1",
	"TO": "keyword1",
	"TOP": "keyword1",
	"TOTALED": "keyword1",
	"TOTALING": "keyword1",
	"TRACE": "keyword1",
	"TRACK-AREA": "keyword1",
	"TRACK-LIMIT": "keyword1",
	"TRACKS": "keyword1",
	"TRAILING": "keyword1",
	"TRAILING-SIGN": "keyword1",
	"TRANSFORM": "keyword1",
	"TRUE": "keyword1",
	"TYPE": "keyword1",
	"TYPEDEF": "keyword1",
	"UNDERLINE": "keyword1",
	"UNEQUAL": "keyword1",
	"UNIT": "keyword1",
	"UNLOCK": "keyword1",
	"UNSTRING": "keyword1",
	"UNTIL": "keyword1",
	"UP": "keyword1",
	"UPDATE": "keyword1",
	"UPON": "keyword1",
	"UPPER": "keyword1",
	"UPPER-CASE": "keyword2",
	"UPSI-0": "keyword1",
	"UPSI-1": "keyword1",
	"UPSI-2": "keyword1",
	"UPSI-3": "keyword1",
	"UPSI-4": "keyword1",
	"UPSI-5": "keyword1",
	"UPSI-6": "keyword1",
	"UPSI-7": "keyword1",
	"USAGE": "keyword1",
	"USE": "keyword1",
	"USER": "keyword1",
	"USING": "keyword1",
	"VALUE": "keyword1",
	"VALUES": "keyword1",
	"VARIABLE": "keyword1",
	"VARIANCE": "keyword2",
	"VARYING": "keyword1",
	"WAIT": "keyword1",
	"WHEN": "keyword1",
	"WHEN-COMPILED": "keyword2",
	"WITH": "keyword1",
	"WORDS": "keyword1",
	"WORKING-STORAGE": "keyword1",
	"WRITE": "keyword1",
	"WRITE-ONLY": "keyword1",
	"WRITE-VERIFY": "keyword1",
	"ZERO": "keyword1",
	"ZERO-FILL": "keyword1",
	"ZEROES": "keyword1",
	"ZEROS": "keyword1",
	"[COPY-PREFIX]": "literal2",
	"[COUNT]": "literal2",
	"[DISPLAY]": "literal2",
	"[EXECUTE]": "literal2",
	"[PG]": "literal2",
	"[PREFIX]": "literal2",
	"[PROGRAM]": "literal2",
	"[SPECIAL-PREFIX]": "literal2",
	"[TESTCASE]": "literal2",
}

# Dictionary of keywords dictionaries for cobol mode.
keywordsDictDict = {
	"cobol_main": cobol_main_keywords_dict,
}

# Rules for cobol_main ruleset.

def rule0(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment1", seq="*",
        at_line_start=True, at_whitespace_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule1(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="\"", end="\"",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule2(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="'", end="'",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule3(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="=",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule4(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq=" >=",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule5(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq=" <=",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule6(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="+",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule7(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="-",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule8(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="/",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule9(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="*",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule10(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="**",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule11(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq=" > ",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule12(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq=" < ",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule13(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="%",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule14(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq=" & ",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule15(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="|",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule16(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="^",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule17(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="~",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule18(colorer, s, i):
    return colorer.match_span(s, i, kind="comment2", begin="EXEC SQL", end="END-EXEC",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule19(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules dict for main ruleset.
rulesDict1 = {
	" ": [rule4,rule5,rule11,rule12,rule14,],
	"\"": [rule1,],
	"%": [rule13,],
	"'": [rule2,],
	"*": [rule0,rule9,rule10,],
	"+": [rule6,],
	"-": [rule7,],
	"/": [rule8,],
	"0": [rule19,],
	"1": [rule19,],
	"2": [rule19,],
	"3": [rule19,],
	"4": [rule19,],
	"5": [rule19,],
	"6": [rule19,],
	"7": [rule19,],
	"8": [rule19,],
	"9": [rule19,],
	"=": [rule3,],
	"@": [rule19,],
	"A": [rule19,],
	"B": [rule19,],
	"C": [rule19,],
	"D": [rule19,],
	"E": [rule18,rule19,],
	"F": [rule19,],
	"G": [rule19,],
	"H": [rule19,],
	"I": [rule19,],
	"J": [rule19,],
	"K": [rule19,],
	"L": [rule19,],
	"M": [rule19,],
	"N": [rule19,],
	"O": [rule19,],
	"P": [rule19,],
	"Q": [rule19,],
	"R": [rule19,],
	"S": [rule19,],
	"T": [rule19,],
	"U": [rule19,],
	"V": [rule19,],
	"W": [rule19,],
	"X": [rule19,],
	"Y": [rule19,],
	"Z": [rule19,],
	"^": [rule16,],
	"_": [rule19,],
	"a": [rule19,],
	"b": [rule19,],
	"c": [rule19,],
	"d": [rule19,],
	"e": [rule19,],
	"f": [rule19,],
	"g": [rule19,],
	"h": [rule19,],
	"i": [rule19,],
	"j": [rule19,],
	"k": [rule19,],
	"l": [rule19,],
	"m": [rule19,],
	"n": [rule19,],
	"o": [rule19,],
	"p": [rule19,],
	"q": [rule19,],
	"r": [rule19,],
	"s": [rule19,],
	"t": [rule19,],
	"u": [rule19,],
	"v": [rule19,],
	"w": [rule19,],
	"x": [rule19,],
	"y": [rule19,],
	"z": [rule19,],
	"|": [rule15,],
	"~": [rule17,],
}

# x.rulesDictDict for cobol mode.
rulesDictDict = {
	"cobol_main": rulesDict1,
}

# Import dict for cobol mode.
importDict = {}

