# Leo colorizer control file for doxygen mode.

# Properties for doxygen mode.
properties = {
	"lineComment": "#",
}

# Keywords dict for doxygen_main ruleset.
doxygen_main_keywords_dict = {
	"
": "keywords",
	"        ": "keywords",
	"            ": "keywords",
	"NO": "keyword3",
	"YES": "keyword2",
}

# Keywords dict for doxygen_doxygen ruleset.
doxygen_doxygen_keywords_dict = {
	"
": "keywords",
	"        ": "keywords",
	"            ": "keywords",
	"&": "label",
	"<": "label",
	">": "label",
	"@": "label",
	"@#": "label",
	"@$": "label",
	"@%": "label",
	"@@": "label",
	"@\": "label",
	"@a": "label",
	"@addindex": "label",
	"@addtogroup": "label",
	"@anchor": "label",
	"@arg": "label",
	"@attention": "label",
	"@author": "label",
	"@b": "label",
	"@brief": "label",
	"@bug": "label",
	"@c": "label",
	"@callgraph": "label",
	"@category": "label",
	"@class": "label",
	"@code": "label",
	"@copydoc": "label",
	"@date": "label",
	"@def": "label",
	"@defgroup": "label",
	"@deprecated": "label",
	"@dontinclude": "label",
	"@dot": "label",
	"@dotfile": "label",
	"@e": "label",
	"@else": "label",
	"@elseif": "label",
	"@em": "label",
	"@endcode": "label",
	"@enddot": "label",
	"@endhtmlonly": "label",
	"@endif": "label",
	"@endlatexonly": "label",
	"@endlink": "label",
	"@endmanonly": "label",
	"@endverbatim": "label",
	"@endxmlonly": "label",
	"@enum": "label",
	"@example": "label",
	"@exception": "label",
	"@f$": "label",
	"@f[": "label",
	"@f]": "label",
	"@file": "label",
	"@fn": "label",
	"@hideinitializer": "label",
	"@htmlinclude": "label",
	"@htmlonly": "label",
	"@if": "label",
	"@ifnot": "label",
	"@image": "label",
	"@include": "label",
	"@includelineno": "label",
	"@ingroup": "label",
	"@interface": "label",
	"@internal": "label",
	"@invariant": "label",
	"@latexonly": "label",
	"@li": "label",
	"@line": "label",
	"@link": "label",
	"@mainpage": "label",
	"@manonly": "label",
	"@n": "label",
	"@name": "label",
	"@namespace": "label",
	"@nosubgrouping": "label",
	"@note": "label",
	"@overload": "label",
	"@p": "label",
	"@package": "label",
	"@page": "label",
	"@par": "label",
	"@paragraph": "label",
	"@param": "label",
	"@param[in,out]": "label",
	"@param[in]": "label",
	"@param[out]": "label",
	"@post": "label",
	"@pre": "label",
	"@private": "label",
	"@privatesection": "label",
	"@property": "label",
	"@protected": "label",
	"@protectedsection": "label",
	"@protocol": "label",
	"@public": "label",
	"@publicsection": "label",
	"@ref": "label",
	"@relates": "label",
	"@relatesalso": "label",
	"@remarks": "label",
	"@return": "label",
	"@retval": "label",
	"@sa": "label",
	"@section": "label",
	"@showinitializer": "label",
	"@since": "label",
	"@skip": "label",
	"@skipline": "label",
	"@struct": "label",
	"@subsection": "label",
	"@subsubsection": "label",
	"@test": "label",
	"@throw": "label",
	"@todo": "label",
	"@typedef": "label",
	"@union": "label",
	"@until": "label",
	"@var": "label",
	"@verbatim": "label",
	"@verbinclude": "label",
	"@version": "label",
	"@warning": "label",
	"@weakgroup": "label",
	"@xmlonly": "label",
	"@xrefitem": "label",
	"@~": "label",
	"\": "label",
	"\#": "label",
	"\$": "label",
	"\%": "label",
	"\@": "label",
	"\\": "label",
	"\a": "label",
	"\addindex": "label",
	"\addtogroup": "label",
	"\anchor": "label",
	"\arg": "label",
	"\attention": "label",
	"\author": "label",
	"\b": "label",
	"\brief": "label",
	"\bug": "label",
	"\c": "label",
	"\callgraph": "label",
	"\category": "label",
	"\class": "label",
	"\code": "label",
	"\copydoc": "label",
	"\date": "label",
	"\def": "label",
	"\defgroup": "label",
	"\deprecated": "label",
	"\dontinclude": "label",
	"\dot": "label",
	"\dotfile": "label",
	"\e": "label",
	"\else": "label",
	"\elseif": "label",
	"\em": "label",
	"\endcode": "label",
	"\enddot": "label",
	"\endhtmlonly": "label",
	"\endif": "label",
	"\endlatexonly": "label",
	"\endlink": "label",
	"\endmanonly": "label",
	"\endverbatim": "label",
	"\endxmlonly": "label",
	"\enum": "label",
	"\example": "label",
	"\exception": "label",
	"\f$": "label",
	"\f[": "label",
	"\f]": "label",
	"\file": "label",
	"\fn": "label",
	"\hideinitializer": "label",
	"\htmlinclude": "label",
	"\htmlonly": "label",
	"\if": "label",
	"\ifnot": "label",
	"\image": "label",
	"\include": "label",
	"\includelineno": "label",
	"\ingroup": "label",
	"\interface": "label",
	"\internal": "label",
	"\invariant": "label",
	"\latexonly": "label",
	"\li": "label",
	"\line": "label",
	"\link": "label",
	"\mainpage": "label",
	"\manonly": "label",
	"\n": "label",
	"\name": "label",
	"\namespace": "label",
	"\nosubgrouping": "label",
	"\note": "label",
	"\overload": "label",
	"\p": "label",
	"\package": "label",
	"\page": "label",
	"\par": "label",
	"\paragraph": "label",
	"\param": "label",
	"\param[in,out]": "label",
	"\param[in]": "label",
	"\param[out]": "label",
	"\post": "label",
	"\pre": "label",
	"\private": "label",
	"\privatesection": "label",
	"\property": "label",
	"\protected": "label",
	"\protectedsection": "label",
	"\protocol": "label",
	"\public": "label",
	"\publicsection": "label",
	"\ref": "label",
	"\relates": "label",
	"\relatesalso": "label",
	"\remarks": "label",
	"\return": "label",
	"\retval": "label",
	"\sa": "label",
	"\section": "label",
	"\showinitializer": "label",
	"\since": "label",
	"\skip": "label",
	"\skipline": "label",
	"\struct": "label",
	"\subsection": "label",
	"\subsubsection": "label",
	"\test": "label",
	"\throw": "label",
	"\todo": "label",
	"\typedef": "label",
	"\union": "label",
	"\until": "label",
	"\var": "label",
	"\verbatim": "label",
	"\verbinclude": "label",
	"\version": "label",
	"\warning": "label",
	"\weakgroup": "label",
	"\xmlonly": "label",
	"\xrefitem": "label",
	"\~": "label",
}

# Dictionary of keywords dictionaries for doxygen mode.
keywordsDictDict = {
	"doxygen_doxygen": doxygen_doxygen_keywords_dict,
	"doxygen_main": doxygen_main_keywords_dict,
}

# Rules for doxygen_main ruleset.

def rule0(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment1", seq="#",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule1(colorer, s, i):
    return colorer.match_mark_previous(s, i, kind="keyword1", pattern="=",
        at_line_start=True, at_whitespace_end=False, at_word_start=False, exclude_match=True)

def rule2(colorer, s, i):
    return colorer.match_mark_previous(s, i, kind="keyword1", pattern="+=",
        at_line_start=True, at_whitespace_end=False, at_word_start=False, exclude_match=True)

def rule3(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="\"", end="\"",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule4(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="'", end="'",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule5(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="`", end="`",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule6(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules dict for main ruleset.
rulesDict1 = {
	"\"": [rule3,],
	"#": [rule0,],
	"'": [rule4,],
	"+": [rule2,],
	"0": [rule6,],
	"1": [rule6,],
	"2": [rule6,],
	"3": [rule6,],
	"4": [rule6,],
	"5": [rule6,],
	"6": [rule6,],
	"7": [rule6,],
	"8": [rule6,],
	"9": [rule6,],
	"=": [rule1,],
	"@": [rule6,],
	"A": [rule6,],
	"B": [rule6,],
	"C": [rule6,],
	"D": [rule6,],
	"E": [rule6,],
	"F": [rule6,],
	"G": [rule6,],
	"H": [rule6,],
	"I": [rule6,],
	"J": [rule6,],
	"K": [rule6,],
	"L": [rule6,],
	"M": [rule6,],
	"N": [rule6,],
	"O": [rule6,],
	"P": [rule6,],
	"Q": [rule6,],
	"R": [rule6,],
	"S": [rule6,],
	"T": [rule6,],
	"U": [rule6,],
	"V": [rule6,],
	"W": [rule6,],
	"X": [rule6,],
	"Y": [rule6,],
	"Z": [rule6,],
	"_": [rule6,],
	"`": [rule5,],
	"a": [rule6,],
	"b": [rule6,],
	"c": [rule6,],
	"d": [rule6,],
	"e": [rule6,],
	"f": [rule6,],
	"g": [rule6,],
	"h": [rule6,],
	"i": [rule6,],
	"j": [rule6,],
	"k": [rule6,],
	"l": [rule6,],
	"m": [rule6,],
	"n": [rule6,],
	"o": [rule6,],
	"p": [rule6,],
	"q": [rule6,],
	"r": [rule6,],
	"s": [rule6,],
	"t": [rule6,],
	"u": [rule6,],
	"v": [rule6,],
	"w": [rule6,],
	"x": [rule6,],
	"y": [rule6,],
	"z": [rule6,],
}

# Rules for doxygen_doxygen ruleset.

def rule7(colorer, s, i):
    return colorer.match_seq(s, i, kind="comment3", seq="*",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule8(colorer, s, i):
    return colorer.match_span(s, i, kind="comment1", begin="<!--", end="-->",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule9(colorer, s, i):
    return colorer.match_seq(s, i, kind="comment3", seq="<<",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule10(colorer, s, i):
    return colorer.match_seq(s, i, kind="comment3", seq="<=",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule11(colorer, s, i):
    return colorer.match_seq(s, i, kind="comment3", seq="< ",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, delegate="")

def rule12(colorer, s, i):
    return colorer.match_span(s, i, kind="markup", begin="<", end=">",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="xml::TAGS",exclude_match=False,
        no_escape=False, no_line_break=True, no_word_break=False)

def rule13(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules dict for doxygen ruleset.
rulesDict1 = {
	"*": [rule7,],
	"0": [rule13,],
	"1": [rule13,],
	"2": [rule13,],
	"3": [rule13,],
	"4": [rule13,],
	"5": [rule13,],
	"6": [rule13,],
	"7": [rule13,],
	"8": [rule13,],
	"9": [rule13,],
	"<": [rule8,rule9,rule10,rule11,rule12,],
	"@": [rule13,],
	"A": [rule13,],
	"B": [rule13,],
	"C": [rule13,],
	"D": [rule13,],
	"E": [rule13,],
	"F": [rule13,],
	"G": [rule13,],
	"H": [rule13,],
	"I": [rule13,],
	"J": [rule13,],
	"K": [rule13,],
	"L": [rule13,],
	"M": [rule13,],
	"N": [rule13,],
	"O": [rule13,],
	"P": [rule13,],
	"Q": [rule13,],
	"R": [rule13,],
	"S": [rule13,],
	"T": [rule13,],
	"U": [rule13,],
	"V": [rule13,],
	"W": [rule13,],
	"X": [rule13,],
	"Y": [rule13,],
	"Z": [rule13,],
	"_": [rule13,],
	"a": [rule13,],
	"b": [rule13,],
	"c": [rule13,],
	"d": [rule13,],
	"e": [rule13,],
	"f": [rule13,],
	"g": [rule13,],
	"h": [rule13,],
	"i": [rule13,],
	"j": [rule13,],
	"k": [rule13,],
	"l": [rule13,],
	"m": [rule13,],
	"n": [rule13,],
	"o": [rule13,],
	"p": [rule13,],
	"q": [rule13,],
	"r": [rule13,],
	"s": [rule13,],
	"t": [rule13,],
	"u": [rule13,],
	"v": [rule13,],
	"w": [rule13,],
	"x": [rule13,],
	"y": [rule13,],
	"z": [rule13,],
}

# x.rulesDictDict for doxygen mode.
rulesDictDict = {
	"doxygen_doxygen": rulesDict1,
	"doxygen_main": rulesDict1,
}

# Import dict for doxygen mode.
importDict = {}

