# Leo colorizer control file for i4gl mode.

# Properties for i4gl mode.
properties = {
	"commentEnd": "}",
	"commentStart": "{",
	"lineComment": "--",
	"noWordSep": "_",
	"wordBreakChars": ",+-=<>/?^&*",
}

# Keywords dict for i4gl_main ruleset.
i4gl_main_keywords_dict = {
	"ABORT": "keyword1",
	"ABS": "keyword1",
	"ABSOLUTE": "keyword1",
	"ACCEPT": "keyword1",
	"ACCESS": "keyword1",
	"ACOS": "keyword1",
	"ADA": "keyword1",
	"ADD": "keyword1",
	"AFTER": "keyword1",
	"ALL": "keyword1",
	"ALLOCATE": "keyword1",
	"ALTER": "keyword1",
	"AND": "keyword1",
	"ANSI": "keyword1",
	"ANY": "keyword1",
	"APPEND": "keyword1",
	"ARG_VAL": "keyword1",
	"ARRAY": "keyword1",
	"ARR_COUNT": "keyword1",
	"ARR_CURR": "keyword1",
	"AS": "keyword1",
	"ASC": "keyword1",
	"ASCENDING": "keyword1",
	"ASCII": "keyword1",
	"ASIN": "keyword1",
	"AT": "keyword1",
	"ATAN": "keyword1",
	"ATAN2": "keyword1",
	"ATTACH": "keyword1",
	"ATTRIBUTE": "keyword1",
	"ATTRIBUTES": "keyword1",
	"AUDIT": "keyword1",
	"AUTHORIZATION": "keyword1",
	"AUTO": "keyword1",
	"AUTONEXT": "keyword1",
	"AVERAGE": "keyword1",
	"AVG": "keyword1",
	"BEFORE": "keyword1",
	"BEGIN": "keyword1",
	"BETWEEN": "keyword1",
	"BLACK": "keyword1",
	"BLINK": "keyword1",
	"BLUE": "keyword1",
	"BOLD": "keyword1",
	"BORDER": "keyword1",
	"BOTH": "keyword1",
	"BOTTOM": "keyword1",
	"BREAK": "keyword1",
	"BUFFERED": "keyword1",
	"BY": "keyword1",
	"BYTE": "keyword1",
	"CALL": "keyword1",
	"CASCADE": "keyword1",
	"CASE": "keyword1",
	"CHAR": "keyword1",
	"CHARACTER": "keyword1",
	"CHARACTER_LENGTH": "keyword1",
	"CHAR_LENGTH": "keyword1",
	"CHECK": "keyword1",
	"CLASS_ORIGIN": "keyword1",
	"CLEAR": "keyword1",
	"CLIPPED": "keyword1",
	"CLOSE": "keyword1",
	"CLUSTER": "keyword1",
	"COBOL": "keyword1",
	"COLOR": "keyword1",
	"COLUMN": "keyword1",
	"COLUMNS": "keyword1",
	"COMMAND": "keyword1",
	"COMMENT": "keyword1",
	"COMMENTS": "keyword1",
	"COMMIT": "keyword1",
	"COMMITTED": "keyword1",
	"COMPOSITES": "keyword1",
	"COMPRESS": "keyword1",
	"CONCURRENT": "keyword1",
	"CONNECT": "keyword1",
	"CONNECTION": "keyword1",
	"CONNECTION_ALIAS": "keyword1",
	"CONSTRAINED": "keyword1",
	"CONSTRAINT": "keyword1",
	"CONSTRAINTS": "keyword1",
	"CONSTRUCT": "keyword1",
	"CONTINUE": "keyword1",
	"CONTROL": "keyword1",
	"COS": "keyword1",
	"COUNT": "keyword1",
	"CREATE": "keyword1",
	"CURRENT": "keyword1",
	"CURSOR": "keyword1",
	"CYAN": "keyword1",
	"DATA": "keyword1",
	"DATABASE": "keyword1",
	"DATASKIP": "keyword1",
	"DATE": "keyword1",
	"DATETIME": "keyword1",
	"DAY": "keyword1",
	"DBA": "keyword1",
	"DBINFO": "keyword1",
	"DBSERVERNAME": "keyword1",
	"DEALLOCATE": "keyword1",
	"DEBUG": "keyword1",
	"DEC": "keyword1",
	"DECIMAL": "keyword1",
	"DECLARE": "keyword1",
	"DEFAULT": "keyword1",
	"DEFAULTS": "keyword1",
	"DEFER": "keyword1",
	"DEFERRED": "keyword1",
	"DEFINE": "keyword1",
	"DELETE": "keyword1",
	"DELIMITER": "keyword1",
	"DELIMITERS": "keyword1",
	"DESC": "keyword1",
	"DESCENDING": "keyword1",
	"DESCRIBE": "keyword1",
	"DESCRIPTOR": "keyword1",
	"DETACH": "keyword1",
	"DIAGNOSTICS": "keyword1",
	"DIM": "keyword1",
	"DIRTY": "keyword1",
	"DISABLED": "keyword1",
	"DISCONNECT": "keyword1",
	"DISPLAY": "keyword1",
	"DISTINCT": "keyword1",
	"DISTRIBUTIONS": "keyword1",
	"DO": "keyword1",
	"DORMANT": "keyword1",
	"DOUBLE": "keyword1",
	"DOWN": "keyword1",
	"DOWNSHIFT": "keyword1",
	"DROP": "keyword1",
	"EACH": "keyword1",
	"ELIF": "keyword1",
	"ELSE": "keyword1",
	"ENABLED": "keyword1",
	"END": "keyword1",
	"ENTRY": "keyword1",
	"ERROR": "keyword1",
	"ERRORLOG": "keyword1",
	"ERR_GET": "keyword1",
	"ERR_PRINT": "keyword1",
	"ERR_QUIT": "keyword1",
	"ESC": "keyword1",
	"ESCAPE": "keyword1",
	"EVERY": "keyword1",
	"EXCEPTION": "keyword1",
	"EXCLUSIVE": "keyword1",
	"EXEC": "keyword1",
	"EXECUTE": "keyword1",
	"EXISTS": "keyword1",
	"EXIT": "keyword1",
	"EXP": "keyword1",
	"EXPLAIN": "keyword1",
	"EXPRESSION": "keyword1",
	"EXTEND": "keyword1",
	"EXTENT": "keyword1",
	"EXTERN": "keyword1",
	"EXTERNAL": "keyword1",
	"F1": "keyword1",
	"F10": "keyword1",
	"F11": "keyword1",
	"F12": "keyword1",
	"F13": "keyword1",
	"F14": "keyword1",
	"F15": "keyword1",
	"F16": "keyword1",
	"F17": "keyword1",
	"F18": "keyword1",
	"F19": "keyword1",
	"F2": "keyword1",
	"F20": "keyword1",
	"F21": "keyword1",
	"F22": "keyword1",
	"F23": "keyword1",
	"F24": "keyword1",
	"F25": "keyword1",
	"F26": "keyword1",
	"F27": "keyword1",
	"F28": "keyword1",
	"F29": "keyword1",
	"F3": "keyword1",
	"F30": "keyword1",
	"F31": "keyword1",
	"F32": "keyword1",
	"F33": "keyword1",
	"F34": "keyword1",
	"F35": "keyword1",
	"F36": "keyword1",
	"F37": "keyword1",
	"F38": "keyword1",
	"F39": "keyword1",
	"F4": "keyword1",
	"F40": "keyword1",
	"F41": "keyword1",
	"F42": "keyword1",
	"F43": "keyword1",
	"F44": "keyword1",
	"F45": "keyword1",
	"F46": "keyword1",
	"F47": "keyword1",
	"F48": "keyword1",
	"F49": "keyword1",
	"F5": "keyword1",
	"F50": "keyword1",
	"F51": "keyword1",
	"F52": "keyword1",
	"F53": "keyword1",
	"F54": "keyword1",
	"F55": "keyword1",
	"F56": "keyword1",
	"F57": "keyword1",
	"F58": "keyword1",
	"F59": "keyword1",
	"F6": "keyword1",
	"F60": "keyword1",
	"F61": "keyword1",
	"F62": "keyword1",
	"F63": "keyword1",
	"F64": "keyword1",
	"F7": "keyword1",
	"F8": "keyword1",
	"F9": "keyword1",
	"FALSE": "literal2",
	"FETCH": "keyword1",
	"FGL_GETENV": "keyword1",
	"FGL_KEYVAL": "keyword1",
	"FGL_LASTKEY": "keyword1",
	"FIELD": "keyword1",
	"FIELD_TOUCHED": "keyword1",
	"FILE": "keyword1",
	"FILLFACTOR": "keyword1",
	"FILTERING": "keyword1",
	"FINISH": "keyword1",
	"FIRST": "keyword1",
	"FLOAT": "keyword1",
	"FLUSH": "keyword1",
	"FOR": "keyword1",
	"FOREACH": "keyword1",
	"FOREIGN": "keyword1",
	"FORM": "keyword1",
	"FORMAT": "keyword1",
	"FORMONLY": "keyword1",
	"FORTRAN": "keyword1",
	"FOUND": "keyword1",
	"FRACTION": "keyword1",
	"FRAGMENT": "keyword1",
	"FREE": "keyword1",
	"FROM": "keyword1",
	"FUNCTION": "keyword1",
	"GET_FLDBUF": "keyword1",
	"GLOBAL": "keyword1",
	"GLOBALS": "keyword1",
	"GO": "keyword1",
	"GOTO": "keyword1",
	"GRANT": "keyword1",
	"GREEN": "keyword1",
	"GROUP": "keyword1",
	"HAVING": "keyword1",
	"HEADER": "keyword1",
	"HELP": "keyword1",
	"HEX": "keyword1",
	"HIDE": "keyword1",
	"HIGH": "keyword1",
	"HOLD": "keyword1",
	"HOUR": "keyword1",
	"IDATA": "keyword1",
	"IF": "keyword1",
	"ILENGTH": "keyword1",
	"IMMEDIATE": "keyword1",
	"IN": "keyword1",
	"INCLUDE": "keyword1",
	"INDEX": "keyword1",
	"INDEXES": "keyword1",
	"INDICATOR": "keyword1",
	"INFIELD": "keyword1",
	"INIT": "keyword1",
	"INITIALIZE": "keyword1",
	"INPUT": "keyword1",
	"INSERT": "keyword1",
	"INSTRUCTIONS": "keyword1",
	"INT": "keyword1",
	"INTEGER": "keyword1",
	"INTERRUPT": "keyword1",
	"INTERVAL": "keyword1",
	"INTO": "keyword1",
	"INT_FLAG": "keyword1",
	"INVISIBLE": "keyword1",
	"IS": "keyword1",
	"ISAM": "keyword1",
	"ISOLATION": "keyword1",
	"ITYPE": "keyword1",
	"KEY": "keyword1",
	"LABEL": "keyword1",
	"LANGUAGE": "keyword1",
	"LAST": "keyword1",
	"LEADING": "keyword1",
	"LEFT": "keyword1",
	"LENGTH": "keyword1",
	"LET": "keyword1",
	"LIKE": "keyword1",
	"LINE": "keyword1",
	"LINENO": "keyword1",
	"LINES": "keyword1",
	"LOAD": "keyword1",
	"LOCATE": "keyword1",
	"LOCK": "keyword1",
	"LOG": "keyword1",
	"LOG10": "keyword1",
	"LOGN": "keyword1",
	"LONG": "keyword1",
	"LOW": "keyword1",
	"MAGENTA": "keyword1",
	"MAIN": "keyword1",
	"MARGIN": "keyword1",
	"MATCHES": "keyword1",
	"MAX": "keyword1",
	"MDY": "keyword1",
	"MEDIUM": "keyword1",
	"MEMORY": "keyword1",
	"MENU": "keyword1",
	"MESSAGE": "keyword1",
	"MESSAGE_LENGTH": "keyword1",
	"MESSAGE_TEXT": "keyword1",
	"MIN": "keyword1",
	"MINUTE": "keyword1",
	"MOD": "keyword1",
	"MODE": "keyword1",
	"MODIFY": "keyword1",
	"MODULE": "keyword1",
	"MONEY": "keyword1",
	"MONTH": "keyword1",
	"MORE": "keyword1",
	"NAME": "keyword1",
	"NCHAR": "keyword1",
	"NEED": "keyword1",
	"NEW": "keyword1",
	"NEXT": "keyword1",
	"NEXTPAGE": "keyword1",
	"NO": "keyword1",
	"NOCR": "keyword1",
	"NOENTRY": "keyword1",
	"NONE": "keyword1",
	"NORMAL": "keyword1",
	"NOT": "keyword1",
	"NOTFOUND": "keyword1",
	"NULL": "literal2",
	"NULLABLE": "keyword1",
	"NUMBER": "keyword1",
	"NUMERIC": "keyword1",
	"NUM_ARGS": "keyword1",
	"NVARCHAR": "keyword1",
	"OCTET_LENGTH": "keyword1",
	"OF": "keyword1",
	"OFF": "keyword1",
	"OLD": "keyword1",
	"ON": "keyword1",
	"ONLY": "keyword1",
	"OPEN": "keyword1",
	"OPTIMIZATION": "keyword1",
	"OPTION": "keyword1",
	"OPTIONS": "keyword1",
	"OR": "keyword1",
	"ORDER": "keyword1",
	"OTHERWISE": "keyword1",
	"OUTER": "keyword1",
	"OUTPUT": "keyword1",
	"PAGE": "keyword1",
	"PAGENO": "keyword1",
	"PASCAL": "keyword1",
	"PAUSE": "keyword1",
	"PDQPRIORITY": "keyword1",
	"PERCENT": "keyword1",
	"PICTURE": "keyword1",
	"PIPE": "keyword1",
	"PLI": "keyword1",
	"POW": "keyword1",
	"PRECISION": "keyword1",
	"PREPARE": "keyword1",
	"PREVIOUS": "keyword1",
	"PREVPAGE": "keyword1",
	"PRIMARY": "keyword1",
	"PRINT": "keyword1",
	"PRINTER": "keyword1",
	"PRIOR": "keyword1",
	"PRIVATE": "keyword1",
	"PRIVILEGES": "keyword1",
	"PROCEDURE": "keyword1",
	"PROGRAM": "keyword1",
	"PROMPT": "keyword1",
	"PUBLIC": "keyword1",
	"PUT": "keyword1",
	"QUIT": "keyword1",
	"QUIT_FLAG": "keyword1",
	"RAISE": "keyword1",
	"RANGE": "keyword1",
	"READ": "keyword1",
	"READONLY": "keyword1",
	"REAL": "keyword1",
	"RECORD": "keyword1",
	"RECOVER": "keyword1",
	"RED": "keyword1",
	"REFERENCES": "keyword1",
	"REFERENCING": "keyword1",
	"REGISTER": "keyword1",
	"RELATIVE": "keyword1",
	"REMAINDER": "keyword1",
	"REMOVE": "keyword1",
	"RENAME": "keyword1",
	"REOPTIMIZATION": "keyword1",
	"REPEATABLE": "keyword1",
	"REPORT": "keyword1",
	"REQUIRED": "keyword1",
	"RESOLUTION": "keyword1",
	"RESOURCE": "keyword1",
	"RESTRICT": "keyword1",
	"RESUME": "keyword1",
	"RETURN": "keyword1",
	"RETURNED_SQLSTATE": "keyword1",
	"RETURNING": "keyword1",
	"REVERSE": "keyword1",
	"REVOKE": "keyword1",
	"RIGHT": "keyword1",
	"ROBIN": "keyword1",
	"ROLE": "keyword1",
	"ROLLBACK": "keyword1",
	"ROLLFORWARD": "keyword1",
	"ROOT": "keyword1",
	"ROUND": "keyword1",
	"ROW": "keyword1",
	"ROWID": "keyword1",
	"ROWIDS": "keyword1",
	"ROWS": "keyword1",
	"ROW_COUNT": "keyword1",
	"RUN": "keyword1",
	"SCALE": "keyword1",
	"SCHEMA": "keyword1",
	"SCREEN": "keyword1",
	"SCROLL": "keyword1",
	"SCR_LINE": "keyword1",
	"SECOND": "keyword1",
	"SECTION": "keyword1",
	"SELECT": "keyword1",
	"SERIAL": "keyword1",
	"SERIALIZABLE": "keyword1",
	"SERVER_NAME": "keyword1",
	"SESSION": "keyword1",
	"SET": "keyword1",
	"SET_COUNT": "keyword1",
	"SHARE": "keyword1",
	"SHORT": "keyword1",
	"SHOW": "keyword1",
	"SITENAME": "keyword1",
	"SIZE": "keyword1",
	"SIZEOF": "keyword1",
	"SKIP": "keyword1",
	"SLEEP": "keyword1",
	"SMALLFLOAT": "keyword1",
	"SMALLINT": "keyword1",
	"SOME": "keyword1",
	"SPACE": "keyword1",
	"SPACES": "keyword1",
	"SQL": "keyword1",
	"SQLAWARN": "keyword1",
	"SQLCA": "keyword1",
	"SQLCODE": "keyword1",
	"SQLERRD": "keyword1",
	"SQLERRM": "keyword1",
	"SQLERROR": "keyword1",
	"SQLERRP": "keyword1",
	"SQLSTATE": "keyword1",
	"SQLWARNING": "keyword1",
	"SQRT": "keyword1",
	"STABILITY": "keyword1",
	"START": "keyword1",
	"STARTLOG": "keyword1",
	"STATIC": "keyword1",
	"STATISTICS": "keyword1",
	"STATUS": "keyword1",
	"STDEV": "keyword1",
	"STEP": "keyword1",
	"STOP": "keyword1",
	"STRING": "keyword1",
	"STRUCT": "keyword1",
	"SUBCLASS_ORIGIN": "keyword1",
	"SUM": "keyword1",
	"SWITCH": "keyword1",
	"SYNONYM": "keyword1",
	"SYSTEM": "keyword1",
	"SysBlobs": "keyword1",
	"SysChecks": "keyword1",
	"SysColAuth": "keyword1",
	"SysColDepend": "keyword1",
	"SysColumns": "keyword1",
	"SysConstraints": "keyword1",
	"SysDefaults": "keyword1",
	"SysDepend": "keyword1",
	"SysDistrib": "keyword1",
	"SysFragAuth": "keyword1",
	"SysFragments": "keyword1",
	"SysIndexes": "keyword1",
	"SysObjState": "keyword1",
	"SysOpClstr": "keyword1",
	"SysProcAuth": "keyword1",
	"SysProcBody": "keyword1",
	"SysProcPlan": "keyword1",
	"SysProcedures": "keyword1",
	"SysReferences": "keyword1",
	"SysRoleAuth": "keyword1",
	"SysSynTable": "keyword1",
	"SysSynonyms": "keyword1",
	"SysTabAuth": "keyword1",
	"SysTables": "keyword1",
	"SysTrigBody": "keyword1",
	"SysTriggers": "keyword1",
	"SysUsers": "keyword1",
	"SysViews": "keyword1",
	"SysViolations": "keyword1",
	"TAB": "keyword1",
	"TABLE": "keyword1",
	"TABLES": "keyword1",
	"TAN": "keyword1",
	"TEMP": "keyword1",
	"TEXT": "keyword1",
	"THEN": "keyword1",
	"THROUGH": "keyword1",
	"THRU": "keyword1",
	"TIME": "keyword1",
	"TO": "keyword1",
	"TODAY": "keyword1",
	"TOP": "keyword1",
	"TOTAL": "keyword1",
	"TRACE": "keyword1",
	"TRAILER": "keyword1",
	"TRAILING": "keyword1",
	"TRANSACTION": "keyword1",
	"TRIGGER": "keyword1",
	"TRIGGERS": "keyword1",
	"TRIM": "keyword1",
	"TRUE": "literal2",
	"TRUNC": "keyword1",
	"TYPE": "keyword1",
	"TYPEDEF": "keyword1",
	"UNCOMMITTED": "keyword1",
	"UNCONSTRAINED": "keyword1",
	"UNDERLINE": "keyword1",
	"UNION": "keyword1",
	"UNIQUE": "keyword1",
	"UNITS": "keyword1",
	"UNLOAD": "keyword1",
	"UNLOCK": "keyword1",
	"UNSIGNED": "keyword1",
	"UP": "keyword1",
	"UPDATE": "keyword1",
	"UPSHIFT": "keyword1",
	"USER": "keyword1",
	"USING": "keyword1",
	"VALIDATE": "keyword1",
	"VALUE": "keyword1",
	"VALUES": "keyword1",
	"VARCHAR": "keyword1",
	"VARIABLES": "keyword1",
	"VARIANCE": "keyword1",
	"VARYING": "keyword1",
	"VERIFY": "keyword1",
	"VIEW": "keyword1",
	"VIOLATIONS": "keyword1",
	"WAIT": "keyword1",
	"WAITING": "keyword1",
	"WARNING": "keyword1",
	"WEEKDAY": "keyword1",
	"WHEN": "keyword1",
	"WHENEVER": "keyword1",
	"WHERE": "keyword1",
	"WHILE": "keyword1",
	"WHITE": "keyword1",
	"WINDOW": "keyword1",
	"WITH": "keyword1",
	"WITHOUT": "keyword1",
	"WORDWRAP": "keyword1",
	"WORK": "keyword1",
	"WRAP": "keyword1",
	"WRITE": "keyword1",
	"YEAR": "keyword1",
	"YELLOW": "keyword1",
	"ZEROFILL": "keyword1",
}

# Rules for i4gl_main ruleset.

def rule0(colorer, s, i):
    return colorer.match_span(s, i, kind='"literal1"', begin="'", end="'",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule1(colorer, s, i):
    return colorer.match_span(s, i, kind='"literal1"', begin="\"", end="\"",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule2(colorer, s, i):
    return colorer.match_eol_span(s, i, kind='"comment1"', seq="--",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule3(colorer, s, i):
    return colorer.match_eol_span(s, i, kind='"comment1"', seq="#",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule4(colorer, s, i):
    return colorer.match_span(s, i, kind='"comment1"', begin="{", end="}",
        at_line_start=False, at_line_end=False, at_word_start=False,
        delegate="",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule5(colorer, s, i):
    return colorer.match_seq(s, i, kind="null", seq=")",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule6(colorer, s, i):
    return colorer.match_seq(s, i, kind="null", seq="]",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule7(colorer, s, i):
    return colorer.match_seq(s, i, kind="null", seq="[",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule8(colorer, s, i):
    return colorer.match_seq(s, i, kind="null", seq=".",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule9(colorer, s, i):
    return colorer.match_seq(s, i, kind="null", seq=",",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule10(colorer, s, i):
    return colorer.match_seq(s, i, kind="null", seq=";",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule11(colorer, s, i):
    return colorer.match_seq(s, i, kind="null", seq=":",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule12(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="=",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule13(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="==",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule14(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="!=",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule15(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq=">=",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule16(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="<=",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule17(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="<>",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule18(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq=">",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule19(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="<",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule20(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="+",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule21(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="-",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule22(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="/",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule23(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="*",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule24(colorer, s, i):
    return colorer.match_seq(s, i, kind="operator", seq="||",
        at_line_start=False, at_line_end=False, at_word_start=False, delegate="")

def rule25(colorer, s, i):
    return colorer.match_mark_previous(s, i, kind='"function"',
        at_line_start=False, at_line_end=False, at_word_start=False, exclude_match=True)

def rule26(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules list for i4gl_main ruleset.
i4gl_main_rules = [
	rule0, rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9,
	rule10, rule11, rule12, rule13, rule14, rule15, rule16, rule17, rule18, rule19,
	rule20, rule21, rule22, rule23, rule24, rule25, rule26, ]

# Rules dict for i4gl mode.
rulesDict = {
	"i4gl_main": i4gl_main_rules,
}

# Import dict for i4gl mode.
importDict = {}

