# Leo colorizer control file for nsis2 mode.
# This file is in the public domain.

# Properties for nsis2 mode.
properties = {
	"indentNextLine": "\\s*(.*:|(function\\s+.*)|(section\\s+.*)|(subsection\\s+.*))",
	"lineComment": ";",
}

# Attributes dict for nsis2_main ruleset.
nsis2_main_attributes_dict = {
	"default": "NULL",
	"digit_re": "",
	"highlight_digits": "true",
	"ignore_case": "true",
	"no_word_sep": "",
}

# Attributes dict for nsis2_nsis_literal ruleset.
nsis2_nsis_literal_attributes_dict = {
	"default": "LITERAL1",
	"digit_re": "",
	"highlight_digits": "true",
	"ignore_case": "true",
	"no_word_sep": "-{}_",
}

# Dictionary of attributes dictionaries for nsis2 mode.
attributesDictDict = {
	"nsis2_main": nsis2_main_attributes_dict,
	"nsis2_nsis_literal": nsis2_nsis_literal_attributes_dict,
}

# Keywords dict for nsis2_main ruleset.
nsis2_main_keywords_dict = {
	"!addincludedir": "keyword2",
	"!addplugindir": "keyword2",
	"!cd": "keyword2",
	"!define": "keyword2",
	"!echo": "keyword2",
	"!else": "keyword1",
	"!endif": "keyword1",
	"!error": "keyword2",
	"!ifdef": "keyword1",
	"!ifndef": "keyword1",
	"!include": "keyword2",
	"!insertmacro": "keyword2",
	"!macro": "keyword1",
	"!macroend": "keyword1",
	"!packhdr": "keyword2",
	"!system": "keyword2",
	"!undef": "keyword2",
	"!verbose": "keyword2",
	"!warning": "keyword2",
	"$$": "literal3",
	"$0": "keyword3",
	"$1": "keyword3",
	"$2": "keyword3",
	"$3": "keyword3",
	"$4": "keyword3",
	"$5": "keyword3",
	"$6": "keyword3",
	"$7": "keyword3",
	"$8": "keyword3",
	"$9": "keyword3",
	"$CMDLINE": "keyword3",
	"$DESKTOP": "literal3",
	"$EXEDIR": "literal3",
	"$HWNDPARENT": "literal3",
	"$INSTDIR": "keyword3",
	"$LANGUAGE": "keyword3",
	"$OUTDIR": "keyword3",
	"$PLUGINSDIR": "literal3",
	"$PROGRAMFILES": "literal3",
	"$QUICKLAUNCH": "literal3",
	"$R0": "keyword3",
	"$R1": "keyword3",
	"$R2": "keyword3",
	"$R3": "keyword3",
	"$R4": "keyword3",
	"$R5": "keyword3",
	"$R6": "keyword3",
	"$R7": "keyword3",
	"$R8": "keyword3",
	"$R9": "keyword3",
	"$SMPROGRAMS": "literal3",
	"$SMSTARTUP": "literal3",
	"$STARTMENU": "literal3",
	"$SYSDIR": "literal3",
	"$TEMP": "literal3",
	"$WINDIR": "literal3",
	"$\\n": "literal3",
	"$\\r": "literal3",
	"${NSISDIR}": "literal3",
	".onguiinit": "keyword3",
	".oninit": "keyword3",
	".oninstfailed": "keyword3",
	".oninstsuccess": "keyword3",
	".onmouseoversection": "keyword3",
	".onselchange": "keyword3",
	".onuserabort": "keyword3",
	".onverifyinstdir": "keyword3",
	"/0": "keyword4",
	"/COMPONENTSONLYONCUSTOM": "keyword4",
	"/CUSTOMSTRING": "keyword4",
	"/FILESONLY": "keyword4",
	"/IMGID": "keyword4",
	"/ITALIC": "keyword4",
	"/LANG": "keyword4",
	"/NOCUSTOM": "keyword4",
	"/NOUNLOAD": "keyword4",
	"/REBOOTOK": "keyword4",
	"/RESIZETOFIT": "keyword4",
	"/RTL": "keyword4",
	"/SHORT": "keyword4",
	"/SILENT": "keyword4",
	"/STRIKE": "keyword4",
	"/TIMEOUT": "keyword4",
	"/TRIM": "keyword4",
	"/UNDERLINE": "keyword4",
	"/a": "keyword4",
	"/e": "keyword4",
	"/ifempty": "keyword4",
	"/nonfatal": "keyword4",
	"/oname": "keyword4",
	"/r": "keyword4",
	"/windows": "keyword4",
	"ALT": "literal3",
	"ARCHIVE": "literal3",
	"CENTER": "literal3",
	"CONTROL": "literal3",
	"CUR": "literal3",
	"END": "literal3",
	"EXT": "literal3",
	"F1": "literal3",
	"F10": "literal3",
	"F11": "literal3",
	"F12": "literal3",
	"F13": "literal3",
	"F14": "literal3",
	"F15": "literal3",
	"F16": "literal3",
	"F17": "literal3",
	"F18": "literal3",
	"F19": "literal3",
	"F2": "literal3",
	"F20": "literal3",
	"F21": "literal3",
	"F22": "literal3",
	"F23": "literal3",
	"F24": "literal3",
	"F3": "literal3",
	"F4": "literal3",
	"F5": "literal3",
	"F6": "literal3",
	"F7": "literal3",
	"F8": "literal3",
	"F9": "literal3",
	"FILE_ATTRIBUTE_ARCHIVE": "literal3",
	"FILE_ATTRIBUTE_HIDDEN": "literal3",
	"FILE_ATTRIBUTE_NORMAL": "literal3",
	"FILE_ATTRIBUTE_OFFLINE": "literal3",
	"FILE_ATTRIBUTE_READONLY": "literal3",
	"FILE_ATTRIBUTE_SYSTEM": "literal3",
	"FILE_ATTRIBUTE_TEMPORARY": "literal3",
	"HIDDEN": "literal3",
	"HKCC": "literal3",
	"HKCR": "literal3",
	"HKCU": "literal3",
	"HKDD": "literal3",
	"HKLM": "literal3",
	"HKPD": "literal3",
	"HKU": "literal3",
	"IDABORT": "literal3",
	"IDCANCEL": "literal3",
	"IDIGNORE": "literal3",
	"IDNO": "literal3",
	"IDOK": "literal3",
	"IDRETRY": "literal3",
	"IDYES": "literal3",
	"LEFT": "literal3",
	"MB_ABORTRETRYIGNORE": "literal3",
	"MB_DEFBUTTON1": "literal3",
	"MB_DEFBUTTON2": "literal3",
	"MB_DEFBUTTON3": "literal3",
	"MB_DEFBUTTON4": "literal3",
	"MB_ICONEXCLAMATION": "literal3",
	"MB_ICONINFORMATION": "literal3",
	"MB_ICONQUESTION": "literal3",
	"MB_ICONSTOP": "literal3",
	"MB_OK": "literal3",
	"MB_OKCANCEL": "literal3",
	"MB_RETRYCANCEL": "literal3",
	"MB_RIGHT": "literal3",
	"MB_SETFOREGROUND": "literal3",
	"MB_TOPMOST": "literal3",
	"MB_YESNO": "literal3",
	"MB_YESNOCANCEL": "literal3",
	"NORMAL": "literal3",
	"OFFLINE": "literal3",
	"READONLY": "literal3",
	"RIGHT": "literal3",
	"RO": "literal3",
	"SET": "literal3",
	"SHIFT": "literal3",
	"SW_SHOWMAXIMIZED": "literal3",
	"SW_SHOWMINIMIZED": "literal3",
	"SW_SHOWNORMAL": "literal3",
	"SYSTEM": "literal3",
	"TEMPORARY": "literal3",
	"a": "literal3",
	"abort": "keyword1",
	"addbrandingimage": "keyword2",
	"addsize": "keyword2",
	"all": "literal3",
	"allowrootdirinstall": "keyword2",
	"allowskipfiles": "keyword2",
	"alwaysoff": "literal3",
	"auto": "literal3",
	"autoclosewindow": "keyword2",
	"bggradient": "keyword2",
	"both": "literal3",
	"bottom": "literal3",
	"brandingtext": "keyword2",
	"bringtofront": "keyword2",
	"bzip2": "literal3",
	"call": "keyword1",
	"callinstdll": "keyword2",
	"caption": "keyword2",
	"changeui": "keyword2",
	"checkbitmap": "keyword2",
	"checkbox": "literal3",
	"clearerrors": "keyword1",
	"colored": "literal3",
	"completedtext": "keyword2",
	"components": "literal3",
	"componenttext": "keyword2",
	"copyfiles": "keyword2",
	"crccheck": "keyword2",
	"createdirectory": "keyword2",
	"createfont": "keyword2",
	"createshortcut": "keyword2",
	"current": "literal3",
	"custom": "literal3",
	"delete": "keyword2",
	"deleteinisec": "keyword2",
	"deleteinistr": "keyword2",
	"deleteregkey": "keyword2",
	"deleteregvalue": "keyword2",
	"detailprint": "keyword2",
	"detailsbuttontext": "keyword2",
	"dim": "invalid",
	"directory": "literal3",
	"dirshow": "keyword2",
	"dirtext": "keyword2",
	"enumregkey": "keyword2",
	"enumregvalue": "keyword2",
	"exch": "keyword2",
	"exec": "keyword2",
	"execshell": "keyword2",
	"execwait": "keyword2",
	"expandenvstrings": "keyword2",
	"false": "literal3",
	"file": "keyword2",
	"fileclose": "keyword2",
	"fileerrortext": "keyword2",
	"fileopen": "keyword2",
	"fileread": "keyword2",
	"filereadbyte": "keyword2",
	"fileseek": "keyword2",
	"filewrite": "keyword2",
	"filewritebyte": "keyword2",
	"findclose": "keyword2",
	"findfirst": "keyword2",
	"findnext": "keyword2",
	"findwindow": "keyword2",
	"flushini": "keyword2",
	"force": "literal3",
	"function": "keyword1",
	"functionend": "keyword1",
	"getcurinsttype": "keyword2",
	"getcurrentaddress": "keyword2",
	"getdlgitem": "keyword2",
	"getdllversion": "keyword2",
	"getdllversionlocal": "keyword2",
	"getfiletime": "keyword2",
	"getfiletimelocal": "keyword2",
	"getfullpathname": "keyword2",
	"getfunctionaddress": "keyword2",
	"getlabeladdress": "keyword2",
	"gettempfilename": "keyword2",
	"getwindowtext": "keyword2",
	"goto": "keyword1",
	"hide": "literal3",
	"hidewindow": "keyword2",
	"icon": "keyword2",
	"ifabort": "keyword1",
	"iferrors": "keyword1",
	"iffileexists": "keyword1",
	"ifnewer": "literal3",
	"ifrebootflag": "keyword1",
	"initpluginsdir": "keyword2",
	"installbuttontext": "keyword2",
	"installcolors": "keyword2",
	"installdir": "keyword2",
	"installdirregkey": "keyword2",
	"instfiles": "literal3",
	"instprogressflags": "keyword2",
	"insttype": "keyword2",
	"insttypegettext": "keyword2",
	"insttypesettext": "keyword2",
	"intcmp": "keyword1",
	"intcmpu": "keyword1",
	"intfmt": "keyword2",
	"intop": "keyword2",
	"iswindow": "keyword1",
	"langstring": "keyword2",
	"langstringup": "keyword2",
	"license": "literal3",
	"licensebkcolor": "keyword2",
	"licensedata": "keyword2",
	"licenseforceselection": "keyword2",
	"licensetext": "keyword2",
	"listonly": "literal3",
	"loadlanguagefile": "keyword2",
	"logset": "keyword2",
	"logtext": "keyword2",
	"manual": "literal3",
	"messagebox": "keyword1",
	"miscbuttontext": "keyword2",
	"name": "keyword2",
	"nevershow": "literal3",
	"none": "literal3",
	"nop": "keyword2",
	"off": "literal3",
	"on": "literal3",
	"outfile": "keyword2",
	"page": "keyword2",
	"plugindir": "keyword2",
	"pop": "keyword2",
	"push": "keyword2",
	"quit": "keyword1",
	"r": "literal3",
	"radiobuttons": "literal3",
	"readenvstr": "keyword2",
	"readinistr": "keyword2",
	"readregdword": "keyword2",
	"readregstr": "keyword2",
	"reboot": "keyword1",
	"regdll": "keyword2",
	"rename": "keyword2",
	"reservefile": "keyword2",
	"return": "keyword1",
	"rmdir": "keyword2",
	"searchpath": "keyword2",
	"section": "keyword1",
	"sectionend": "keyword1",
	"sectiongetflags": "keyword2",
	"sectiongetinsttypes": "keyword2",
	"sectiongetsize": "keyword2",
	"sectiongettext": "keyword2",
	"sectionin": "keyword2",
	"sectionsetflags": "keyword2",
	"sectionsetinsttypes": "keyword2",
	"sectionsetsize": "keyword2",
	"sectionsettext": "keyword2",
	"sendmessage": "keyword2",
	"setautoclose": "keyword2",
	"setbkcolor": "keyword2",
	"setbrandingimage": "keyword2",
	"setcompress": "keyword2",
	"setcompressor": "keyword2",
	"setcurinsttype": "keyword2",
	"setdatablockoptimize": "keyword2",
	"setdatesave": "keyword2",
	"setdetailsprint": "keyword2",
	"setdetailsview": "keyword2",
	"seterrors": "keyword1",
	"setfileattributes": "keyword2",
	"setfont": "keyword2",
	"setoutpath": "keyword2",
	"setoverwrite": "keyword2",
	"setpluginunload": "keyword2",
	"setrebootflag": "keyword2",
	"setshellvarcontext": "keyword2",
	"setstaticbkcolor": "keyword2",
	"setwindowlong": "keyword2",
	"show": "literal3",
	"showinstdetails": "keyword2",
	"showuninstdetails": "keyword2",
	"showwindow": "keyword2",
	"silent": "literal3",
	"silentinstall": "keyword2",
	"silentlog": "literal3",
	"silentuninstall": "keyword2",
	"sleep": "keyword2",
	"smooth": "literal3",
	"spacetexts": "keyword2",
	"strcmp": "keyword1",
	"strcpy": "keyword2",
	"strlen": "keyword2",
	"subcaption": "keyword2",
	"subsection": "keyword1",
	"subsectionend": "keyword1",
	"textonly": "literal3",
	"top": "literal3",
	"true": "literal3",
	"try": "literal3",
	"un.onguiinit": "keyword3",
	"un.oninit": "keyword3",
	"un.onuninstfailed": "keyword3",
	"un.onuninstsuccess": "keyword3",
	"un.onuserabort": "keyword3",
	"uninstConfirm": "literal3",
	"uninstallbuttontext": "keyword2",
	"uninstallcaption": "keyword2",
	"uninstallexename": "invalid",
	"uninstallicon": "keyword2",
	"uninstallsubcaption": "keyword2",
	"uninstalltext": "keyword2",
	"uninstpage": "keyword2",
	"unregdll": "keyword2",
	"var": "keyword2",
	"viaddversionkey": "keyword2",
	"vicomments": "keyword2",
	"vicompanyname": "keyword2",
	"videscription": "keyword2",
	"vilegalcopyrights": "keyword2",
	"vilegaltrademarks": "keyword2",
	"viproductname": "keyword2",
	"viproductversion": "keyword2",
	"w": "literal3",
	"windowicon": "keyword2",
	"writeinistr": "keyword2",
	"writeregbin": "keyword2",
	"writeregdword": "keyword2",
	"writeregexpandstr": "keyword2",
	"writeregstr": "keyword2",
	"writeuninstaller": "keyword2",
	"xpstyle": "keyword2",
	"zlib": "literal3",
}

# Keywords dict for nsis2_nsis_literal ruleset.
nsis2_nsis_literal_keywords_dict = {}

# Dictionary of keywords dictionaries for nsis2 mode.
keywordsDictDict = {
	"nsis2_main": nsis2_main_keywords_dict,
	"nsis2_nsis_literal": nsis2_nsis_literal_keywords_dict,
}

# Rules for nsis2_main ruleset.

def rule0(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment1", seq=";",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule1(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment2", seq="#",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="", exclude_match=False)

def rule2(colorer, s, i):
    return colorer.match_mark_following(s, i, kind="keyword3", pattern="$",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, exclude_match=False)

def rule3(colorer, s, i):
    return colorer.match_mark_previous(s, i, kind="function", pattern="::",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, exclude_match=True)

def rule4(colorer, s, i):
    return colorer.match_mark_previous(s, i, kind="label", pattern=":",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, exclude_match=True)

def rule5(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="\"", end="\"",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="NSIS_LITERAL",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule6(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="'", end="'",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="NSIS_LITERAL",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule7(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="`", end="`",
        at_line_start=False, at_whitespace_end=False, at_word_start=False,
        delegate="NSIS_LITERAL",exclude_match=False,
        no_escape=False, no_line_break=False, no_word_break=False)

def rule8(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules dict for main ruleset.
rulesDict1 = {
	"!": [rule8,],
	"\"": [rule5,],
	"#": [rule1,],
	"$": [rule2,rule8,],
	"'": [rule6,],
	".": [rule8,],
	"/": [rule8,],
	"0": [rule8,],
	"1": [rule8,],
	"2": [rule8,],
	"3": [rule8,],
	"4": [rule8,],
	"5": [rule8,],
	"6": [rule8,],
	"7": [rule8,],
	"8": [rule8,],
	"9": [rule8,],
	":": [rule3,rule4,],
	";": [rule0,],
	"@": [rule8,],
	"A": [rule8,],
	"B": [rule8,],
	"C": [rule8,],
	"D": [rule8,],
	"E": [rule8,],
	"F": [rule8,],
	"G": [rule8,],
	"H": [rule8,],
	"I": [rule8,],
	"J": [rule8,],
	"K": [rule8,],
	"L": [rule8,],
	"M": [rule8,],
	"N": [rule8,],
	"O": [rule8,],
	"P": [rule8,],
	"Q": [rule8,],
	"R": [rule8,],
	"S": [rule8,],
	"T": [rule8,],
	"U": [rule8,],
	"V": [rule8,],
	"W": [rule8,],
	"X": [rule8,],
	"Y": [rule8,],
	"Z": [rule8,],
	"\\": [rule8,],
	"_": [rule8,],
	"`": [rule7,],
	"a": [rule8,],
	"b": [rule8,],
	"c": [rule8,],
	"d": [rule8,],
	"e": [rule8,],
	"f": [rule8,],
	"g": [rule8,],
	"h": [rule8,],
	"i": [rule8,],
	"j": [rule8,],
	"k": [rule8,],
	"l": [rule8,],
	"m": [rule8,],
	"n": [rule8,],
	"o": [rule8,],
	"p": [rule8,],
	"q": [rule8,],
	"r": [rule8,],
	"s": [rule8,],
	"t": [rule8,],
	"u": [rule8,],
	"v": [rule8,],
	"w": [rule8,],
	"x": [rule8,],
	"y": [rule8,],
	"z": [rule8,],
	"{": [rule8,],
	"}": [rule8,],
}

# Rules for nsis2_nsis_literal ruleset.

def rule9(colorer, s, i):
    return colorer.match_mark_following(s, i, kind="keyword3", pattern="$",
        at_line_start=False, at_whitespace_end=False, at_word_start=False, exclude_match=False)

# Rules dict for nsis_literal ruleset.
rulesDict2 = {
	"$": [rule9,],
}

# x.rulesDictDict for nsis2 mode.
rulesDictDict = {
	"nsis2_main": rulesDict1,
	"nsis2_nsis_literal": rulesDict2,
}

# Import dict for nsis2 mode.
importDict = {}

